(cl:in-package util-msg)
(cl:export '(HEADER-VAL
          HEADER
          ANT_E-VAL
          ANT_E
          ANT_N-VAL
          ANT_N
          ANT_U-VAL
          ANT_U
          ANT_YAW-VAL
          ANT_YAW
          DUAL_YAW-VAL
          DUAL_YAW
          DUAL_E-VAL
          DUAL_E
          DUAL_N-VAL
          DUAL_N
          DUAL_U-VAL
          DUAL_U
          SLAM_X-VAL
          SLAM_X
          SLAM_Y-VAL
          SLAM_Y
          ERR_E-VAL
          ERR_E
          ERR_N-VAL
          ERR_N
          ERR_U-VAL
          ERR_U
          ERR_YAW-VAL
          ERR_YAW
          ERR_SLAME-VAL
          ERR_SLAME
          ERR_SLAMN-VAL
          ERR_SLAMN
          ERR_SLAMU-VAL
          ERR_SLAMU
          ERR_SLAMYAW-VAL
          ERR_SLAMYAW
))