(cl:in-package util-msg)
(cl:export '(HEADER-VAL
          HEADER
          PLAT_ID-VAL
          PLAT_ID
          ERROR_CODE-VAL
          ERROR_CODE
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECOND-VAL
          GPS_MILLISECOND
          DR_X-VAL
          DR_X
          DR_Y-VAL
          DR_Y
          DR_Z-VAL
          DR_Z
          DR_HEADING-VAL
          DR_HEADING
          DR_ROLL-VAL
          DR_ROLL
          DR_PITCH-VAL
          DR_PITCH
          VEHICLE_SPEED-VAL
          VEHICLE_SPEED
          ROT_X-VAL
          ROT_X
          ROT_Y-VAL
          ROT_Y
          ROT_Z-VAL
          ROT_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
))