(cl:in-package util-msg)
(cl:export '(HEADER-VAL
          HEADER
          VALID-VAL
          VALID
          LIO_GENERATION-VAL
          LIO_GENERATION
          IMU_TOPIC-VAL
          IMU_TOPIC
          DURATION_SEC-VAL
          DURATION_SEC
          SAMPLE_COUNT-VAL
          SAMPLE_COUNT
          MEAN_ACCELERATION_MPS2-VAL
          MEAN_ACCELERATION_MPS2
          MEAN_ANGULAR_VELOCITY_RADPS-VAL
          MEAN_ANGULAR_VELOCITY_RADPS
          ACCELERATION_VARIANCE-VAL
          ACCELERATION_VARIANCE
          ANGULAR_VELOCITY_VARIANCE-VAL
          ANGULAR_VELOCITY_VARIANCE
          MAX_ANGULAR_VELOCITY_NORM_RADPS-VAL
          MAX_ANGULAR_VELOCITY_NORM_RADPS
))