// Generated by gencpp from file util/GpsPosition.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_GPSPOSITION_H
#define UTIL_MESSAGE_GPSPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct GpsPosition_
{
  typedef GpsPosition_<ContainerAllocator> Type;

  GpsPosition_()
    : header()
    , plat_id(0)
    , error_code(0)
    , gps_flag(0)
    , positionStatus(0)
    , gps_week(0)
    , gps_millisecond(0)
    , longitude(0.0)
    , latitude(0.0)
    , height(0.0)
    , gaussX(0.0)
    , gaussY(0.0)
    , pitch(0.0)
    , roll(0.0)
    , azimuth(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)
    , northVelocity(0.0)
    , eastVelocity(0.0)
    , upVelocity(0.0)
    , gps_confidence(0)
    , INS_GpsFlag_Pos(0)
    , INS_NumSV(0)
    , INS_GpsFlag_Heading(0)
    , INS_Gps_Age(0)
    , INS_Car_Status(0)
    , INS_Status(0)
    , INS_VehicleAlign(0)
    , INS_Std_Lat(0.0)
    , INS_Std_Lon(0.0)
    , INS_Std_LocatHeight(0.0)
    , INS_Std_Heading(0.0)  {
    }
  GpsPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , plat_id(0)
    , error_code(0)
    , gps_flag(0)
    , positionStatus(0)
    , gps_week(0)
    , gps_millisecond(0)
    , longitude(0.0)
    , latitude(0.0)
    , height(0.0)
    , gaussX(0.0)
    , gaussY(0.0)
    , pitch(0.0)
    , roll(0.0)
    , azimuth(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)
    , northVelocity(0.0)
    , eastVelocity(0.0)
    , upVelocity(0.0)
    , gps_confidence(0)
    , INS_GpsFlag_Pos(0)
    , INS_NumSV(0)
    , INS_GpsFlag_Heading(0)
    , INS_Gps_Age(0)
    , INS_Car_Status(0)
    , INS_Status(0)
    , INS_VehicleAlign(0)
    , INS_Std_Lat(0.0)
    , INS_Std_Lon(0.0)
    , INS_Std_LocatHeight(0.0)
    , INS_Std_Heading(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _plat_id_type;
  _plat_id_type plat_id;

   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef int32_t _gps_flag_type;
  _gps_flag_type gps_flag;

   typedef int32_t _positionStatus_type;
  _positionStatus_type positionStatus;

   typedef uint32_t _gps_week_type;
  _gps_week_type gps_week;

   typedef uint32_t _gps_millisecond_type;
  _gps_millisecond_type gps_millisecond;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _height_type;
  _height_type height;

   typedef double _gaussX_type;
  _gaussX_type gaussX;

   typedef double _gaussY_type;
  _gaussY_type gaussY;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _azimuth_type;
  _azimuth_type azimuth;

   typedef double _acc_x_type;
  _acc_x_type acc_x;

   typedef double _acc_y_type;
  _acc_y_type acc_y;

   typedef double _acc_z_type;
  _acc_z_type acc_z;

   typedef double _rot_x_type;
  _rot_x_type rot_x;

   typedef double _rot_y_type;
  _rot_y_type rot_y;

   typedef double _rot_z_type;
  _rot_z_type rot_z;

   typedef double _northVelocity_type;
  _northVelocity_type northVelocity;

   typedef double _eastVelocity_type;
  _eastVelocity_type eastVelocity;

   typedef double _upVelocity_type;
  _upVelocity_type upVelocity;

   typedef int32_t _gps_confidence_type;
  _gps_confidence_type gps_confidence;

   typedef uint8_t _INS_GpsFlag_Pos_type;
  _INS_GpsFlag_Pos_type INS_GpsFlag_Pos;

   typedef uint8_t _INS_NumSV_type;
  _INS_NumSV_type INS_NumSV;

   typedef uint8_t _INS_GpsFlag_Heading_type;
  _INS_GpsFlag_Heading_type INS_GpsFlag_Heading;

   typedef uint8_t _INS_Gps_Age_type;
  _INS_Gps_Age_type INS_Gps_Age;

   typedef uint8_t _INS_Car_Status_type;
  _INS_Car_Status_type INS_Car_Status;

   typedef uint8_t _INS_Status_type;
  _INS_Status_type INS_Status;

   typedef uint8_t _INS_VehicleAlign_type;
  _INS_VehicleAlign_type INS_VehicleAlign;

   typedef double _INS_Std_Lat_type;
  _INS_Std_Lat_type INS_Std_Lat;

   typedef double _INS_Std_Lon_type;
  _INS_Std_Lon_type INS_Std_Lon;

   typedef double _INS_Std_LocatHeight_type;
  _INS_Std_LocatHeight_type INS_Std_LocatHeight;

   typedef double _INS_Std_Heading_type;
  _INS_Std_Heading_type INS_Std_Heading;





  typedef boost::shared_ptr< ::util::GpsPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::GpsPosition_<ContainerAllocator> const> ConstPtr;

}; // struct GpsPosition_

typedef ::util::GpsPosition_<std::allocator<void> > GpsPosition;

typedef boost::shared_ptr< ::util::GpsPosition > GpsPositionPtr;
typedef boost::shared_ptr< ::util::GpsPosition const> GpsPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::GpsPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::GpsPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::GpsPosition_<ContainerAllocator1> & lhs, const ::util::GpsPosition_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.plat_id == rhs.plat_id &&
    lhs.error_code == rhs.error_code &&
    lhs.gps_flag == rhs.gps_flag &&
    lhs.positionStatus == rhs.positionStatus &&
    lhs.gps_week == rhs.gps_week &&
    lhs.gps_millisecond == rhs.gps_millisecond &&
    lhs.longitude == rhs.longitude &&
    lhs.latitude == rhs.latitude &&
    lhs.height == rhs.height &&
    lhs.gaussX == rhs.gaussX &&
    lhs.gaussY == rhs.gaussY &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.azimuth == rhs.azimuth &&
    lhs.acc_x == rhs.acc_x &&
    lhs.acc_y == rhs.acc_y &&
    lhs.acc_z == rhs.acc_z &&
    lhs.rot_x == rhs.rot_x &&
    lhs.rot_y == rhs.rot_y &&
    lhs.rot_z == rhs.rot_z &&
    lhs.northVelocity == rhs.northVelocity &&
    lhs.eastVelocity == rhs.eastVelocity &&
    lhs.upVelocity == rhs.upVelocity &&
    lhs.gps_confidence == rhs.gps_confidence &&
    lhs.INS_GpsFlag_Pos == rhs.INS_GpsFlag_Pos &&
    lhs.INS_NumSV == rhs.INS_NumSV &&
    lhs.INS_GpsFlag_Heading == rhs.INS_GpsFlag_Heading &&
    lhs.INS_Gps_Age == rhs.INS_Gps_Age &&
    lhs.INS_Car_Status == rhs.INS_Car_Status &&
    lhs.INS_Status == rhs.INS_Status &&
    lhs.INS_VehicleAlign == rhs.INS_VehicleAlign &&
    lhs.INS_Std_Lat == rhs.INS_Std_Lat &&
    lhs.INS_Std_Lon == rhs.INS_Std_Lon &&
    lhs.INS_Std_LocatHeight == rhs.INS_Std_LocatHeight &&
    lhs.INS_Std_Heading == rhs.INS_Std_Heading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::GpsPosition_<ContainerAllocator1> & lhs, const ::util::GpsPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::GpsPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::GpsPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::GpsPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::GpsPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::GpsPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::GpsPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::GpsPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f75c3f5644c5aad5a6320ced80a0264c";
  }

  static const char* value(const ::util::GpsPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf75c3f5644c5aad5ULL;
  static const uint64_t static_value2 = 0xa6320ced80a0264cULL;
};

template<class ContainerAllocator>
struct DataType< ::util::GpsPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/GpsPosition";
  }

  static const char* value(const ::util::GpsPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::GpsPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#GpsPosition\n"
"Header header\n"
"int32 plat_id			#标识此消息的平台id\n"
"int32 error_code		#错误标识码\n"
"int32 gps_flag			#GPS状态\n"
"int32 positionStatus		#系统运行状态\n"
"\n"
"uint32 gps_week			#GPS Week\n"
"\n"
"uint32 gps_millisecond		#GPS millisecond in a week\n"
"\n"
"float64 longitude		#经纬度，单位为度\n"
"float64 latitude\n"
"float64 height			#海拔,单位为m\n"
"\n"
"float64 gaussX			#高斯投影位置,cm\n"
"float64 gaussY\n"
"\n"
"\n"
"float64 pitch			#俯仰角,x轴方向(正右方)右手定则四指方向为正,单位为0.01度\n"
"float64 roll			#翻滚角,y轴方向(正前方)右手定则四指方向为正,单位为0.01度\n"
"float64 azimuth			#航向角，单位为0.01度,向东为零度，逆时针0-360\n"
"\n"
"float64 acc_x # m/s2\n"
"float64 acc_y\n"
"float64 acc_z\n"
"\n"
"float64 rot_x # deg/s\n"
"float64 rot_y\n"
"float64 rot_z\n"
"\n"
"float64 northVelocity		#north速度，单位为cm/s\n"
"float64 eastVelocity		#east速度,单位为cm/s\n"
"float64 upVelocity		#up速度,单位为cm/s\n"
"\n"
"int32 gps_confidence	#gps定位精度置信度,根据卫星数量和INS,POS解算状态综合得出, 8-10为良好,6-7为一般,小于等于5为信号差,0为没有信号\n"
"\n"
"uint8 INS_GpsFlag_Pos\n"
"uint8 INS_NumSV\n"
"uint8 INS_GpsFlag_Heading\n"
"uint8 INS_Gps_Age\n"
"uint8 INS_Car_Status\n"
"uint8 INS_Status\n"
"uint8 INS_VehicleAlign\n"
"float64 INS_Std_Lat\n"
"float64 INS_Std_Lon\n"
"float64 INS_Std_LocatHeight\n"
"float64 INS_Std_Heading\n"
"\n"
"#float64 speed_now   #由northVelocity和eastVelocity计算得到的当前车速\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::GpsPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::GpsPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.plat_id);
      stream.next(m.error_code);
      stream.next(m.gps_flag);
      stream.next(m.positionStatus);
      stream.next(m.gps_week);
      stream.next(m.gps_millisecond);
      stream.next(m.longitude);
      stream.next(m.latitude);
      stream.next(m.height);
      stream.next(m.gaussX);
      stream.next(m.gaussY);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.azimuth);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
      stream.next(m.rot_x);
      stream.next(m.rot_y);
      stream.next(m.rot_z);
      stream.next(m.northVelocity);
      stream.next(m.eastVelocity);
      stream.next(m.upVelocity);
      stream.next(m.gps_confidence);
      stream.next(m.INS_GpsFlag_Pos);
      stream.next(m.INS_NumSV);
      stream.next(m.INS_GpsFlag_Heading);
      stream.next(m.INS_Gps_Age);
      stream.next(m.INS_Car_Status);
      stream.next(m.INS_Status);
      stream.next(m.INS_VehicleAlign);
      stream.next(m.INS_Std_Lat);
      stream.next(m.INS_Std_Lon);
      stream.next(m.INS_Std_LocatHeight);
      stream.next(m.INS_Std_Heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::GpsPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::GpsPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "plat_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.plat_id);
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "gps_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gps_flag);
    s << indent << "positionStatus: ";
    Printer<int32_t>::stream(s, indent + "  ", v.positionStatus);
    s << indent << "gps_week: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.gps_week);
    s << indent << "gps_millisecond: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.gps_millisecond);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "gaussX: ";
    Printer<double>::stream(s, indent + "  ", v.gaussX);
    s << indent << "gaussY: ";
    Printer<double>::stream(s, indent + "  ", v.gaussY);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "azimuth: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth);
    s << indent << "acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.acc_z);
    s << indent << "rot_x: ";
    Printer<double>::stream(s, indent + "  ", v.rot_x);
    s << indent << "rot_y: ";
    Printer<double>::stream(s, indent + "  ", v.rot_y);
    s << indent << "rot_z: ";
    Printer<double>::stream(s, indent + "  ", v.rot_z);
    s << indent << "northVelocity: ";
    Printer<double>::stream(s, indent + "  ", v.northVelocity);
    s << indent << "eastVelocity: ";
    Printer<double>::stream(s, indent + "  ", v.eastVelocity);
    s << indent << "upVelocity: ";
    Printer<double>::stream(s, indent + "  ", v.upVelocity);
    s << indent << "gps_confidence: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gps_confidence);
    s << indent << "INS_GpsFlag_Pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_GpsFlag_Pos);
    s << indent << "INS_NumSV: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_NumSV);
    s << indent << "INS_GpsFlag_Heading: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_GpsFlag_Heading);
    s << indent << "INS_Gps_Age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_Gps_Age);
    s << indent << "INS_Car_Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_Car_Status);
    s << indent << "INS_Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_Status);
    s << indent << "INS_VehicleAlign: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.INS_VehicleAlign);
    s << indent << "INS_Std_Lat: ";
    Printer<double>::stream(s, indent + "  ", v.INS_Std_Lat);
    s << indent << "INS_Std_Lon: ";
    Printer<double>::stream(s, indent + "  ", v.INS_Std_Lon);
    s << indent << "INS_Std_LocatHeight: ";
    Printer<double>::stream(s, indent + "  ", v.INS_Std_LocatHeight);
    s << indent << "INS_Std_Heading: ";
    Printer<double>::stream(s, indent + "  ", v.INS_Std_Heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_GPSPOSITION_H
