// Generated by gencpp from file util/VehicleReport.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_VEHICLEREPORT_H
#define UTIL_MESSAGE_VEHICLEREPORT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct VehicleReport_
{
  typedef VehicleReport_<ContainerAllocator> Type;

  VehicleReport_()
    : header()
    , vehicle_gear(0)
    , clamping_brake_status(0)
    , drive_mode_state(0)
    , vcu_speed_req(0.0)
    , vehicle_soc(0)
    , vehicle_status_msgcntr(0)
    , vehicle_speed(0.0)
    , vehicle_brake_pressure(0.0)
    , vehicle_steering_angle(0.0)
    , vehicle_status_2_msgcntr(0.0)  {
    }
  VehicleReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicle_gear(0)
    , clamping_brake_status(0)
    , drive_mode_state(0)
    , vcu_speed_req(0.0)
    , vehicle_soc(0)
    , vehicle_status_msgcntr(0)
    , vehicle_speed(0.0)
    , vehicle_brake_pressure(0.0)
    , vehicle_steering_angle(0.0)
    , vehicle_status_2_msgcntr(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _vehicle_gear_type;
  _vehicle_gear_type vehicle_gear;

   typedef uint8_t _clamping_brake_status_type;
  _clamping_brake_status_type clamping_brake_status;

   typedef uint8_t _drive_mode_state_type;
  _drive_mode_state_type drive_mode_state;

   typedef float _vcu_speed_req_type;
  _vcu_speed_req_type vcu_speed_req;

   typedef uint8_t _vehicle_soc_type;
  _vehicle_soc_type vehicle_soc;

   typedef uint8_t _vehicle_status_msgcntr_type;
  _vehicle_status_msgcntr_type vehicle_status_msgcntr;

   typedef float _vehicle_speed_type;
  _vehicle_speed_type vehicle_speed;

   typedef float _vehicle_brake_pressure_type;
  _vehicle_brake_pressure_type vehicle_brake_pressure;

   typedef float _vehicle_steering_angle_type;
  _vehicle_steering_angle_type vehicle_steering_angle;

   typedef float _vehicle_status_2_msgcntr_type;
  _vehicle_status_2_msgcntr_type vehicle_status_2_msgcntr;





  typedef boost::shared_ptr< ::util::VehicleReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::VehicleReport_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleReport_

typedef ::util::VehicleReport_<std::allocator<void> > VehicleReport;

typedef boost::shared_ptr< ::util::VehicleReport > VehicleReportPtr;
typedef boost::shared_ptr< ::util::VehicleReport const> VehicleReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::VehicleReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::VehicleReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::VehicleReport_<ContainerAllocator1> & lhs, const ::util::VehicleReport_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vehicle_gear == rhs.vehicle_gear &&
    lhs.clamping_brake_status == rhs.clamping_brake_status &&
    lhs.drive_mode_state == rhs.drive_mode_state &&
    lhs.vcu_speed_req == rhs.vcu_speed_req &&
    lhs.vehicle_soc == rhs.vehicle_soc &&
    lhs.vehicle_status_msgcntr == rhs.vehicle_status_msgcntr &&
    lhs.vehicle_speed == rhs.vehicle_speed &&
    lhs.vehicle_brake_pressure == rhs.vehicle_brake_pressure &&
    lhs.vehicle_steering_angle == rhs.vehicle_steering_angle &&
    lhs.vehicle_status_2_msgcntr == rhs.vehicle_status_2_msgcntr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::VehicleReport_<ContainerAllocator1> & lhs, const ::util::VehicleReport_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::VehicleReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::VehicleReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::VehicleReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::VehicleReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::VehicleReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::VehicleReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::VehicleReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8141fbcf1c26eb79107a5ea125eaf0a9";
  }

  static const char* value(const ::util::VehicleReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8141fbcf1c26eb79ULL;
  static const uint64_t static_value2 = 0x107a5ea125eaf0a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::VehicleReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/VehicleReport";
  }

  static const char* value(const ::util::VehicleReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::VehicleReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# 0x303\n"
"uint8 vehicle_gear\n"
"uint8 clamping_brake_status\n"
"uint8 drive_mode_state\n"
"float32 vcu_speed_req\n"
"uint8 vehicle_soc\n"
"uint8 vehicle_status_msgcntr\n"
"\n"
"# 0x304\n"
"float32 vehicle_speed\n"
"float32 vehicle_brake_pressure\n"
"float32 vehicle_steering_angle\n"
"float32 vehicle_status_2_msgcntr\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::VehicleReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::VehicleReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicle_gear);
      stream.next(m.clamping_brake_status);
      stream.next(m.drive_mode_state);
      stream.next(m.vcu_speed_req);
      stream.next(m.vehicle_soc);
      stream.next(m.vehicle_status_msgcntr);
      stream.next(m.vehicle_speed);
      stream.next(m.vehicle_brake_pressure);
      stream.next(m.vehicle_steering_angle);
      stream.next(m.vehicle_status_2_msgcntr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::VehicleReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::VehicleReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicle_gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vehicle_gear);
    s << indent << "clamping_brake_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clamping_brake_status);
    s << indent << "drive_mode_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.drive_mode_state);
    s << indent << "vcu_speed_req: ";
    Printer<float>::stream(s, indent + "  ", v.vcu_speed_req);
    s << indent << "vehicle_soc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vehicle_soc);
    s << indent << "vehicle_status_msgcntr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vehicle_status_msgcntr);
    s << indent << "vehicle_speed: ";
    Printer<float>::stream(s, indent + "  ", v.vehicle_speed);
    s << indent << "vehicle_brake_pressure: ";
    Printer<float>::stream(s, indent + "  ", v.vehicle_brake_pressure);
    s << indent << "vehicle_steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.vehicle_steering_angle);
    s << indent << "vehicle_status_2_msgcntr: ";
    Printer<float>::stream(s, indent + "  ", v.vehicle_status_2_msgcntr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_VEHICLEREPORT_H
