# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from util/PerceptionStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class PerceptionStatus(genpy.Message):
  _md5sum = "ab035d44aff8214d3f26c118b7695eb3"
  _type = "util/PerceptionStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
bool lidar2BaselinkStatus
bool lidar2CameraStatus
bool cameraIntrinsicStatus
bool distcoeffStatus
bool pointcloudStatus
bool poseStatus
bool yoloStatus

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','lidar2BaselinkStatus','lidar2CameraStatus','cameraIntrinsicStatus','distcoeffStatus','pointcloudStatus','poseStatus','yoloStatus']
  _slot_types = ['std_msgs/Header','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lidar2BaselinkStatus,lidar2CameraStatus,cameraIntrinsicStatus,distcoeffStatus,pointcloudStatus,poseStatus,yoloStatus

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PerceptionStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lidar2BaselinkStatus is None:
        self.lidar2BaselinkStatus = False
      if self.lidar2CameraStatus is None:
        self.lidar2CameraStatus = False
      if self.cameraIntrinsicStatus is None:
        self.cameraIntrinsicStatus = False
      if self.distcoeffStatus is None:
        self.distcoeffStatus = False
      if self.pointcloudStatus is None:
        self.pointcloudStatus = False
      if self.poseStatus is None:
        self.poseStatus = False
      if self.yoloStatus is None:
        self.yoloStatus = False
    else:
      self.header = std_msgs.msg.Header()
      self.lidar2BaselinkStatus = False
      self.lidar2CameraStatus = False
      self.cameraIntrinsicStatus = False
      self.distcoeffStatus = False
      self.pointcloudStatus = False
      self.poseStatus = False
      self.yoloStatus = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7B().pack(_x.lidar2BaselinkStatus, _x.lidar2CameraStatus, _x.cameraIntrinsicStatus, _x.distcoeffStatus, _x.pointcloudStatus, _x.poseStatus, _x.yoloStatus))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.lidar2BaselinkStatus, _x.lidar2CameraStatus, _x.cameraIntrinsicStatus, _x.distcoeffStatus, _x.pointcloudStatus, _x.poseStatus, _x.yoloStatus,) = _get_struct_7B().unpack(str[start:end])
      self.lidar2BaselinkStatus = bool(self.lidar2BaselinkStatus)
      self.lidar2CameraStatus = bool(self.lidar2CameraStatus)
      self.cameraIntrinsicStatus = bool(self.cameraIntrinsicStatus)
      self.distcoeffStatus = bool(self.distcoeffStatus)
      self.pointcloudStatus = bool(self.pointcloudStatus)
      self.poseStatus = bool(self.poseStatus)
      self.yoloStatus = bool(self.yoloStatus)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7B().pack(_x.lidar2BaselinkStatus, _x.lidar2CameraStatus, _x.cameraIntrinsicStatus, _x.distcoeffStatus, _x.pointcloudStatus, _x.poseStatus, _x.yoloStatus))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.lidar2BaselinkStatus, _x.lidar2CameraStatus, _x.cameraIntrinsicStatus, _x.distcoeffStatus, _x.pointcloudStatus, _x.poseStatus, _x.yoloStatus,) = _get_struct_7B().unpack(str[start:end])
      self.lidar2BaselinkStatus = bool(self.lidar2BaselinkStatus)
      self.lidar2CameraStatus = bool(self.lidar2CameraStatus)
      self.cameraIntrinsicStatus = bool(self.cameraIntrinsicStatus)
      self.distcoeffStatus = bool(self.distcoeffStatus)
      self.pointcloudStatus = bool(self.pointcloudStatus)
      self.poseStatus = bool(self.poseStatus)
      self.yoloStatus = bool(self.yoloStatus)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7B = None
def _get_struct_7B():
    global _struct_7B
    if _struct_7B is None:
        _struct_7B = struct.Struct("<7B")
    return _struct_7B
