(cl:in-package util-msg)
(cl:export '(HEADER-VAL
          HEADER
          VEHICLE_GEAR-VAL
          VEHICLE_GEAR
          CLAMPING_BRAKE_STATUS-VAL
          CLAMPING_BRAKE_STATUS
          DRIVE_MODE_STATE-VAL
          DRIVE_MODE_STATE
          VCU_SPEED_REQ-VAL
          VCU_SPEED_REQ
          VEHICLE_SOC-VAL
          VEHICLE_SOC
          VEHICLE_STATUS_MSGCNTR-VAL
          VEHICLE_STATUS_MSGCNTR
          VEHICLE_SPEED-VAL
          VEHICLE_SPEED
          VEHICLE_BRAKE_PRESSURE-VAL
          VEHICLE_BRAKE_PRESSURE
          VEHICLE_STEERING_ANGLE-VAL
          VEHICLE_STEERING_ANGLE
          VEHICLE_STATUS_2_MSGCNTR-VAL
          VEHICLE_STATUS_2_MSGCNTR
))