// Generated by gencpp from file pure_pursuit/TurnCompletedResponse.msg
// DO NOT EDIT!


#ifndef PURE_PURSUIT_MESSAGE_TURNCOMPLETEDRESPONSE_H
#define PURE_PURSUIT_MESSAGE_TURNCOMPLETEDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pure_pursuit
{
template <class ContainerAllocator>
struct TurnCompletedResponse_
{
  typedef TurnCompletedResponse_<ContainerAllocator> Type;

  TurnCompletedResponse_()
    : turn_finish(false)  {
    }
  TurnCompletedResponse_(const ContainerAllocator& _alloc)
    : turn_finish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _turn_finish_type;
  _turn_finish_type turn_finish;





  typedef boost::shared_ptr< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TurnCompletedResponse_

typedef ::pure_pursuit::TurnCompletedResponse_<std::allocator<void> > TurnCompletedResponse;

typedef boost::shared_ptr< ::pure_pursuit::TurnCompletedResponse > TurnCompletedResponsePtr;
typedef boost::shared_ptr< ::pure_pursuit::TurnCompletedResponse const> TurnCompletedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator1> & lhs, const ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.turn_finish == rhs.turn_finish;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator1> & lhs, const ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pure_pursuit

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dae0339b58aaeeee6587b8e576a925bb";
  }

  static const char* value(const ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdae0339b58aaeeeeULL;
  static const uint64_t static_value2 = 0x6587b8e576a925bbULL;
};

template<class ContainerAllocator>
struct DataType< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pure_pursuit/TurnCompletedResponse";
  }

  static const char* value(const ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool turn_finish\n"
"\n"
;
  }

  static const char* value(const ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turn_finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnCompletedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pure_pursuit::TurnCompletedResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "turn_finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turn_finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PURE_PURSUIT_MESSAGE_TURNCOMPLETEDRESPONSE_H
