// Generated by gencpp from file obstacle_avoidance/Point2DArray.msg
// DO NOT EDIT!


#ifndef OBSTACLE_AVOIDANCE_MESSAGE_POINT2DARRAY_H
#define OBSTACLE_AVOIDANCE_MESSAGE_POINT2DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <obstacle_avoidance/Point2D.h>

namespace obstacle_avoidance
{
template <class ContainerAllocator>
struct Point2DArray_
{
  typedef Point2DArray_<ContainerAllocator> Type;

  Point2DArray_()
    : points()  {
    }
  Point2DArray_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::obstacle_avoidance::Point2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::obstacle_avoidance::Point2D_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct Point2DArray_

typedef ::obstacle_avoidance::Point2DArray_<std::allocator<void> > Point2DArray;

typedef boost::shared_ptr< ::obstacle_avoidance::Point2DArray > Point2DArrayPtr;
typedef boost::shared_ptr< ::obstacle_avoidance::Point2DArray const> Point2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_avoidance::Point2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::obstacle_avoidance::Point2DArray_<ContainerAllocator1> & lhs, const ::obstacle_avoidance::Point2DArray_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::obstacle_avoidance::Point2DArray_<ContainerAllocator1> & lhs, const ::obstacle_avoidance::Point2DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace obstacle_avoidance

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0083ddac30f807eeef29c66ffedb79c7";
  }

  static const char* value(const ::obstacle_avoidance::Point2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0083ddac30f807eeULL;
  static const uint64_t static_value2 = 0xef29c66ffedb79c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_avoidance/Point2DArray";
  }

  static const char* value(const ::obstacle_avoidance::Point2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point2D[] points  # Array of Point2D\n"
"\n"
"================================================================================\n"
"MSG: obstacle_avoidance/Point2D\n"
"# Point2D.msg\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::obstacle_avoidance::Point2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_avoidance::Point2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_avoidance::Point2DArray_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::obstacle_avoidance::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_AVOIDANCE_MESSAGE_POINT2DARRAY_H
