# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mower_msgs/VehicleInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class VehicleInfo(genpy.Message):
  _md5sum = "8a2a4b2a095bc9355e18d7be4b50f3fd"
  _type = "mower_msgs/VehicleInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

# AGVStatus 0x301  现履带车底控无反馈，均不成立
float64 speed_status  
float64 leftw_speed   
float64 rightw_speed
uint8 gear_model      
uint8 drive_mode
uint8 mow_height
uint8 battery_soc

#gear_model
uint8 P_Gear=0 # 0x00： P 档
uint8 R_Gear=1 # 0x01： 倒档R
uint8 N_Gear=2 # 0x02： N 档
uint8 D_Gear=3 # 0x03： D 档
#drive_model
uint8 Manualcontrol_mode=0 # 0x00：手动控制模式
uint8 Automaticcontrol_mode=1 # 0x01：自动控制模式
uint8 Remotecontrol_mode=2 # 0x02：遥控器调试模式
#mow_height
uint8 Low_mode=2 # 0x02：割草高度为低
uint8 Medium_mode=1 # 0x01：割草高度为中
uint8 High_mode=0 # 0x00：割草高度为高


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  P_Gear = 0
  R_Gear = 1
  N_Gear = 2
  D_Gear = 3
  Manualcontrol_mode = 0
  Automaticcontrol_mode = 1
  Remotecontrol_mode = 2
  Low_mode = 2
  Medium_mode = 1
  High_mode = 0

  __slots__ = ['header','speed_status','leftw_speed','rightw_speed','gear_model','drive_mode','mow_height','battery_soc']
  _slot_types = ['std_msgs/Header','float64','float64','float64','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,speed_status,leftw_speed,rightw_speed,gear_model,drive_mode,mow_height,battery_soc

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.speed_status is None:
        self.speed_status = 0.
      if self.leftw_speed is None:
        self.leftw_speed = 0.
      if self.rightw_speed is None:
        self.rightw_speed = 0.
      if self.gear_model is None:
        self.gear_model = 0
      if self.drive_mode is None:
        self.drive_mode = 0
      if self.mow_height is None:
        self.mow_height = 0
      if self.battery_soc is None:
        self.battery_soc = 0
    else:
      self.header = std_msgs.msg.Header()
      self.speed_status = 0.
      self.leftw_speed = 0.
      self.rightw_speed = 0.
      self.gear_model = 0
      self.drive_mode = 0
      self.mow_height = 0
      self.battery_soc = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d4B().pack(_x.speed_status, _x.leftw_speed, _x.rightw_speed, _x.gear_model, _x.drive_mode, _x.mow_height, _x.battery_soc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.speed_status, _x.leftw_speed, _x.rightw_speed, _x.gear_model, _x.drive_mode, _x.mow_height, _x.battery_soc,) = _get_struct_3d4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d4B().pack(_x.speed_status, _x.leftw_speed, _x.rightw_speed, _x.gear_model, _x.drive_mode, _x.mow_height, _x.battery_soc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.speed_status, _x.leftw_speed, _x.rightw_speed, _x.gear_model, _x.drive_mode, _x.mow_height, _x.battery_soc,) = _get_struct_3d4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d4B = None
def _get_struct_3d4B():
    global _struct_3d4B
    if _struct_3d4B is None:
        _struct_3d4B = struct.Struct("<3d4B")
    return _struct_3d4B
