(cl:in-package util-msg)
(cl:export '(HEADER-VAL
          HEADER
          LIDAR2BASELINKSTATUS-VAL
          LIDAR2BASELINKSTATUS
          LIDAR2CAMERASTATUS-VAL
          LIDAR2CAMERASTATUS
          CAMERAINTRINSICSTATUS-VAL
          CAMERAINTRINSICSTATUS
          DISTCOEFFSTATUS-VAL
          DISTCOEFFSTATUS
          POINTCLOUDSTATUS-VAL
          POINTCLOUDSTATUS
          POSESTATUS-VAL
          POSESTATUS
          YOLOSTATUS-VAL
          YOLOSTATUS
))