(cl:in-package util-msg)
(cl:export '(HEADER-VAL
          HEADER
          LOCAL_X-VAL
          LOCAL_X
          LOCAL_Y-VAL
          LOCAL_Y
          GLOBAL_X-VAL
          GLOBAL_X
          GLOBAL_Y-VAL
          GLOBAL_Y
          X1-VAL
          X1
          Y1-VAL
          Y1
          X2-VAL
          X2
          Y2-VAL
          Y2
          X3-VAL
          X3
          Y3-VAL
          Y3
          X4-VAL
          X4
          Y4-VAL
          Y4
          IS_DYNAMIC-VAL
          IS_DYNAMIC
))