(cl:in-package util-msg)
(cl:export '(X1-VAL
          X1
          Y1-VAL
          Y1
          X2-VAL
          X2
          Y2-VAL
          Y2
          X3-VAL
          X3
          Y3-VAL
          Y3
          X4-VAL
          X4
          Y4-VAL
          Y4
          ZMIN-VAL
          ZMIN
          ZMAX-VAL
          ZMAX
          SPEED-VAL
          SPEED
          SPEED_DIRECTION-VAL
          SPEED_DIRECTION
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          GLOBAL_X-VAL
          GLOBAL_X
          GLOBAL_Y-VAL
          GLOBAL_Y
          LOCAL_X-VAL
          LOCAL_X
          LOCAL_Y-VAL
          LOCAL_Y
))