// Generated by gencpp from file util/LIOPose.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_LIOPOSE_H
#define UTIL_MESSAGE_LIOPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct LIOPose_
{
  typedef LIOPose_<ContainerAllocator> Type;

  LIOPose_()
    : header()
    , position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , q_w(0.0)
    , q_x(0.0)
    , q_y(0.0)
    , q_z(0.0)
    , lio_state(false)
    , imu_speed(0.0)
    , imt_static(false)  {
    }
  LIOPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , q_w(0.0)
    , q_x(0.0)
    , q_y(0.0)
    , q_z(0.0)
    , lio_state(false)
    , imu_speed(0.0)
    , imt_static(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _position_x_type;
  _position_x_type position_x;

   typedef double _position_y_type;
  _position_y_type position_y;

   typedef double _position_z_type;
  _position_z_type position_z;

   typedef double _q_w_type;
  _q_w_type q_w;

   typedef double _q_x_type;
  _q_x_type q_x;

   typedef double _q_y_type;
  _q_y_type q_y;

   typedef double _q_z_type;
  _q_z_type q_z;

   typedef uint8_t _lio_state_type;
  _lio_state_type lio_state;

   typedef double _imu_speed_type;
  _imu_speed_type imu_speed;

   typedef uint8_t _imt_static_type;
  _imt_static_type imt_static;





  typedef boost::shared_ptr< ::util::LIOPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::LIOPose_<ContainerAllocator> const> ConstPtr;

}; // struct LIOPose_

typedef ::util::LIOPose_<std::allocator<void> > LIOPose;

typedef boost::shared_ptr< ::util::LIOPose > LIOPosePtr;
typedef boost::shared_ptr< ::util::LIOPose const> LIOPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::LIOPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::LIOPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::LIOPose_<ContainerAllocator1> & lhs, const ::util::LIOPose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_z == rhs.position_z &&
    lhs.q_w == rhs.q_w &&
    lhs.q_x == rhs.q_x &&
    lhs.q_y == rhs.q_y &&
    lhs.q_z == rhs.q_z &&
    lhs.lio_state == rhs.lio_state &&
    lhs.imu_speed == rhs.imu_speed &&
    lhs.imt_static == rhs.imt_static;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::LIOPose_<ContainerAllocator1> & lhs, const ::util::LIOPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::LIOPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::LIOPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::LIOPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::LIOPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::LIOPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::LIOPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::LIOPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc6fba92d9eec750f98200ca1300a109";
  }

  static const char* value(const ::util::LIOPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc6fba92d9eec750ULL;
  static const uint64_t static_value2 = 0xf98200ca1300a109ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::LIOPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/LIOPose";
  }

  static const char* value(const ::util::LIOPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::LIOPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Lidar slam msg\n"
"Header header\n"
"float64 position_x\n"
"float64 position_y\n"
"float64 position_z\n"
"float64 q_w\n"
"float64 q_x\n"
"float64 q_y\n"
"float64 q_z\n"
"bool  lio_state\n"
"float64 imu_speed\n"
"bool imt_static\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::LIOPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::LIOPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_z);
      stream.next(m.q_w);
      stream.next(m.q_x);
      stream.next(m.q_y);
      stream.next(m.q_z);
      stream.next(m.lio_state);
      stream.next(m.imu_speed);
      stream.next(m.imt_static);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LIOPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::LIOPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::LIOPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position_x: ";
    Printer<double>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<double>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_z: ";
    Printer<double>::stream(s, indent + "  ", v.position_z);
    s << indent << "q_w: ";
    Printer<double>::stream(s, indent + "  ", v.q_w);
    s << indent << "q_x: ";
    Printer<double>::stream(s, indent + "  ", v.q_x);
    s << indent << "q_y: ";
    Printer<double>::stream(s, indent + "  ", v.q_y);
    s << indent << "q_z: ";
    Printer<double>::stream(s, indent + "  ", v.q_z);
    s << indent << "lio_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lio_state);
    s << indent << "imu_speed: ";
    Printer<double>::stream(s, indent + "  ", v.imu_speed);
    s << indent << "imt_static: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.imt_static);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_LIOPOSE_H
