# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from util/err.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class err(genpy.Message):
  _md5sum = "1e17d8731f8e0158fd085ddb259f3fb3"
  _type = "util/err"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float64 ant_e
float64 ant_n
float64 ant_u
float64 ant_yaw
float64 dual_yaw
float64 dual_e
float64 dual_n
float64 dual_u
float64 slam_x
float64 slam_y
float64 err_e 
float64 err_n
float64 err_u
float64 err_yaw
float64 err_slame
float64 err_slamn
float64 err_slamu
float64 err_slamyaw 
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','ant_e','ant_n','ant_u','ant_yaw','dual_yaw','dual_e','dual_n','dual_u','slam_x','slam_y','err_e','err_n','err_u','err_yaw','err_slame','err_slamn','err_slamu','err_slamyaw']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ant_e,ant_n,ant_u,ant_yaw,dual_yaw,dual_e,dual_n,dual_u,slam_x,slam_y,err_e,err_n,err_u,err_yaw,err_slame,err_slamn,err_slamu,err_slamyaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(err, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ant_e is None:
        self.ant_e = 0.
      if self.ant_n is None:
        self.ant_n = 0.
      if self.ant_u is None:
        self.ant_u = 0.
      if self.ant_yaw is None:
        self.ant_yaw = 0.
      if self.dual_yaw is None:
        self.dual_yaw = 0.
      if self.dual_e is None:
        self.dual_e = 0.
      if self.dual_n is None:
        self.dual_n = 0.
      if self.dual_u is None:
        self.dual_u = 0.
      if self.slam_x is None:
        self.slam_x = 0.
      if self.slam_y is None:
        self.slam_y = 0.
      if self.err_e is None:
        self.err_e = 0.
      if self.err_n is None:
        self.err_n = 0.
      if self.err_u is None:
        self.err_u = 0.
      if self.err_yaw is None:
        self.err_yaw = 0.
      if self.err_slame is None:
        self.err_slame = 0.
      if self.err_slamn is None:
        self.err_slamn = 0.
      if self.err_slamu is None:
        self.err_slamu = 0.
      if self.err_slamyaw is None:
        self.err_slamyaw = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.ant_e = 0.
      self.ant_n = 0.
      self.ant_u = 0.
      self.ant_yaw = 0.
      self.dual_yaw = 0.
      self.dual_e = 0.
      self.dual_n = 0.
      self.dual_u = 0.
      self.slam_x = 0.
      self.slam_y = 0.
      self.err_e = 0.
      self.err_n = 0.
      self.err_u = 0.
      self.err_yaw = 0.
      self.err_slame = 0.
      self.err_slamn = 0.
      self.err_slamu = 0.
      self.err_slamyaw = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d().pack(_x.ant_e, _x.ant_n, _x.ant_u, _x.ant_yaw, _x.dual_yaw, _x.dual_e, _x.dual_n, _x.dual_u, _x.slam_x, _x.slam_y, _x.err_e, _x.err_n, _x.err_u, _x.err_yaw, _x.err_slame, _x.err_slamn, _x.err_slamu, _x.err_slamyaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 144
      (_x.ant_e, _x.ant_n, _x.ant_u, _x.ant_yaw, _x.dual_yaw, _x.dual_e, _x.dual_n, _x.dual_u, _x.slam_x, _x.slam_y, _x.err_e, _x.err_n, _x.err_u, _x.err_yaw, _x.err_slame, _x.err_slamn, _x.err_slamu, _x.err_slamyaw,) = _get_struct_18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d().pack(_x.ant_e, _x.ant_n, _x.ant_u, _x.ant_yaw, _x.dual_yaw, _x.dual_e, _x.dual_n, _x.dual_u, _x.slam_x, _x.slam_y, _x.err_e, _x.err_n, _x.err_u, _x.err_yaw, _x.err_slame, _x.err_slamn, _x.err_slamu, _x.err_slamyaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 144
      (_x.ant_e, _x.ant_n, _x.ant_u, _x.ant_yaw, _x.dual_yaw, _x.dual_e, _x.dual_n, _x.dual_u, _x.slam_x, _x.slam_y, _x.err_e, _x.err_n, _x.err_u, _x.err_yaw, _x.err_slame, _x.err_slamn, _x.err_slamu, _x.err_slamyaw,) = _get_struct_18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18d = None
def _get_struct_18d():
    global _struct_18d
    if _struct_18d is None:
        _struct_18d = struct.Struct("<18d")
    return _struct_18d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
