# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from util/ImuStaticCalibration.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import std_msgs.msg

class ImuStaticCalibration(genpy.Message):
  _md5sum = "18a255ee627c55f5a95de2c4231b1512"
  _type = "util/ImuStaticCalibration"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# FAST-LIO权威静止初始化窗口统计。消息由/laserMapping锁存发布；
# header.stamp是该静止窗口最后一帧IMU的传感器时间，header.frame_id是原始IMU坐标系。
Header header
bool valid
time lio_generation
string imu_topic
float64 duration_sec
uint32 sample_count
float64[3] mean_acceleration_mps2
float64[3] mean_angular_velocity_radps
float64[3] acceleration_variance
float64[3] angular_velocity_variance
float64 max_angular_velocity_norm_radps

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','valid','lio_generation','imu_topic','duration_sec','sample_count','mean_acceleration_mps2','mean_angular_velocity_radps','acceleration_variance','angular_velocity_variance','max_angular_velocity_norm_radps']
  _slot_types = ['std_msgs/Header','bool','time','string','float64','uint32','float64[3]','float64[3]','float64[3]','float64[3]','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,valid,lio_generation,imu_topic,duration_sec,sample_count,mean_acceleration_mps2,mean_angular_velocity_radps,acceleration_variance,angular_velocity_variance,max_angular_velocity_norm_radps

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ImuStaticCalibration, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.valid is None:
        self.valid = False
      if self.lio_generation is None:
        self.lio_generation = genpy.Time()
      if self.imu_topic is None:
        self.imu_topic = ''
      if self.duration_sec is None:
        self.duration_sec = 0.
      if self.sample_count is None:
        self.sample_count = 0
      if self.mean_acceleration_mps2 is None:
        self.mean_acceleration_mps2 = [0.] * 3
      if self.mean_angular_velocity_radps is None:
        self.mean_angular_velocity_radps = [0.] * 3
      if self.acceleration_variance is None:
        self.acceleration_variance = [0.] * 3
      if self.angular_velocity_variance is None:
        self.angular_velocity_variance = [0.] * 3
      if self.max_angular_velocity_norm_radps is None:
        self.max_angular_velocity_norm_radps = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.valid = False
      self.lio_generation = genpy.Time()
      self.imu_topic = ''
      self.duration_sec = 0.
      self.sample_count = 0
      self.mean_acceleration_mps2 = [0.] * 3
      self.mean_angular_velocity_radps = [0.] * 3
      self.acceleration_variance = [0.] * 3
      self.angular_velocity_variance = [0.] * 3
      self.max_angular_velocity_norm_radps = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.valid, _x.lio_generation.secs, _x.lio_generation.nsecs))
      _x = self.imu_topic
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_dI().pack(_x.duration_sec, _x.sample_count))
      buff.write(_get_struct_3d().pack(*self.mean_acceleration_mps2))
      buff.write(_get_struct_3d().pack(*self.mean_angular_velocity_radps))
      buff.write(_get_struct_3d().pack(*self.acceleration_variance))
      buff.write(_get_struct_3d().pack(*self.angular_velocity_variance))
      _x = self.max_angular_velocity_norm_radps
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lio_generation is None:
        self.lio_generation = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.valid, _x.lio_generation.secs, _x.lio_generation.nsecs,) = _get_struct_B2I().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.imu_topic = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.imu_topic = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.duration_sec, _x.sample_count,) = _get_struct_dI().unpack(str[start:end])
      start = end
      end += 24
      self.mean_acceleration_mps2 = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.mean_angular_velocity_radps = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.acceleration_variance = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.angular_velocity_variance = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 8
      (self.max_angular_velocity_norm_radps,) = _get_struct_d().unpack(str[start:end])
      self.lio_generation.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.valid, _x.lio_generation.secs, _x.lio_generation.nsecs))
      _x = self.imu_topic
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_dI().pack(_x.duration_sec, _x.sample_count))
      buff.write(self.mean_acceleration_mps2.tostring())
      buff.write(self.mean_angular_velocity_radps.tostring())
      buff.write(self.acceleration_variance.tostring())
      buff.write(self.angular_velocity_variance.tostring())
      _x = self.max_angular_velocity_norm_radps
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lio_generation is None:
        self.lio_generation = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.valid, _x.lio_generation.secs, _x.lio_generation.nsecs,) = _get_struct_B2I().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.imu_topic = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.imu_topic = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.duration_sec, _x.sample_count,) = _get_struct_dI().unpack(str[start:end])
      start = end
      end += 24
      self.mean_acceleration_mps2 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.mean_angular_velocity_radps = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.acceleration_variance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.angular_velocity_variance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 8
      (self.max_angular_velocity_norm_radps,) = _get_struct_d().unpack(str[start:end])
      self.lio_generation.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_dI = None
def _get_struct_dI():
    global _struct_dI
    if _struct_dI is None:
        _struct_dI = struct.Struct("<dI")
    return _struct_dI
