# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from util/LocalizationStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class LocalizationStatus(genpy.Message):
  _md5sum = "66d83c808f19f476c7a0fb306057009c"
  _type = "util/LocalizationStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Unified localization lifecycle status.  fusion_4dof publishes the algorithm
# view on /Mower/localization_algorithm_status; android_manager_4dof publishes
# the authoritative aggregate view on /Mower/localization_status.  Both topics
# are latched.
Header header

uint8 MODE_UNKNOWN=0
uint8 MODE_IDLE=1
uint8 MODE_MAPPING=2
uint8 MODE_LOCALIZATION=3

# The user-visible workflow and the algorithm process runtime are deliberately
# separate. During a boundary-recording workflow, a recovery may restart fusion
# in TRACK_SAVED_ORIGIN without ending the MAPPING workflow.
uint8 WORKFLOW_UNKNOWN=0
uint8 WORKFLOW_MAPPING=1
uint8 WORKFLOW_LOCALIZATION=2

uint8 RUNTIME_UNKNOWN=0
uint8 RUNTIME_CREATE_ORIGIN=1
uint8 RUNTIME_TRACK_SAVED_ORIGIN=2

uint8 PHASE_UNKNOWN=0
uint8 PHASE_WAIT_FAST_LIO=1
uint8 PHASE_WAIT_INS=2
uint8 PHASE_WAIT_MAP=3
uint8 PHASE_WAIT_GPS=4
uint8 PHASE_WAIT_ALIGNMENT=5
uint8 PHASE_READY_RTK=6
uint8 PHASE_READY_LIO_LOCKED=7
uint8 PHASE_READY_LIO_SEEDED=8
uint8 PHASE_READY_IMU_RESTRICTED=9
uint8 PHASE_SWITCHING_MAP=10
uint8 PHASE_RESTARTING_FUSION=11
uint8 PHASE_RESTARTING_ALL=12
uint8 PHASE_RECOVERING_LIO=13
uint8 PHASE_FAULT=14
uint8 PHASE_WAIT_IMU_ODOMETRY=15
uint8 PHASE_RESTART_VERIFYING=16
uint8 PHASE_WAIT_ALGORITHM=17
uint8 PHASE_WAIT_TRUSTED_OUTPUT=18

uint8 SOURCE_NONE=0
uint8 SOURCE_RTK=1
uint8 SOURCE_LIO_LOCKED=2
uint8 SOURCE_LIO_SEEDED=3
uint8 SOURCE_IMU_RESTRICTED=4

uint8 RESTART_NONE=0
uint8 RESTART_FUSION=1
uint8 RESTART_LIO=2
uint8 RESTART_ALL=3

uint16 FAULT_NONE=0
uint16 FAULT_MAP_INVALID=1
uint16 FAULT_RESTART_FAILED=2
uint16 FAULT_RESTART_SUPPRESSED=3
uint16 FAULT_POSITION_TIMEOUT=4
uint16 FAULT_LOW_FREQUENCY=5
uint16 FAULT_ALGORITHM=6
uint16 FAULT_RESTART_PARTIAL=7

# Publisher identity and legacy process-mode fields. requested_mode/active_mode
# are retained for compatibility; use workflow_mode plus active_runtime_mode for
# unambiguous new integrations.
string reporter
uint8 requested_mode
uint8 active_mode
uint8 workflow_mode
uint8 requested_runtime_mode
uint8 active_runtime_mode
uint8 phase

# Current production position semantics.
uint8 position_source
uint32 position_state
bool position_valid

# INS readiness. Both ins_solution_good and the compatibility field
# ins_initialized mean that a fresh receiver status has INS_Status==3.
# ins_position_status remains the 1ant publisher's motion-derived heading
# consistency diagnostic; it is not a localization startup gate.
bool ins_status_received
bool ins_solution_good
bool ins_initialized
uint8 ins_status
uint8 ins_vehicle_align
uint8 ins_heading_flag
int32 ins_position_status

# FAST-LIO and alignment truth owned by fusion_4dof.
bool fast_lio_initialized
# Process-generation identity is wall-clock based and used only for equality,
# never for message-age calculations. It lets the manager distinguish a new
# fusion process from a verification failure in the restart wrapper.
bool fusion_generation_valid
uint32 fusion_generation_sec
uint32 fusion_generation_nsec
bool lio_generation_valid
# Process identity may become valid before static calibration. Consumers must
# use fast_lio_initialized for pose readiness.
uint32 lio_generation_sec
uint32 lio_generation_nsec
bool map_origin_ready
bool map_origin_committed
bool alignment_ready
bool alignment_locked
bool imu_odometry_ready
bool gps_good
bool lio_good

# fusion_4dof owns runtime map identity; android_manager_4dof adds requested
# lifecycle state, last-created identity, restart and watchdog ownership.
string active_map
string pending_map
string last_created_map
string active_map_uuid
string pending_map_uuid
uint32 map_schema_version
string coordinate_frame
string origin_checksum
bool map_valid
bool algorithm_status_valid
bool transitioning
bool restart_in_progress
uint8 restart_scope
bool watchdog_position_timeout
bool watchdog_low_frequency
bool automatic_restart_suspended
uint32 automatic_restart_count
bool stop_required
uint16 fault_code
string reason

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  MODE_UNKNOWN = 0
  MODE_IDLE = 1
  MODE_MAPPING = 2
  MODE_LOCALIZATION = 3
  WORKFLOW_UNKNOWN = 0
  WORKFLOW_MAPPING = 1
  WORKFLOW_LOCALIZATION = 2
  RUNTIME_UNKNOWN = 0
  RUNTIME_CREATE_ORIGIN = 1
  RUNTIME_TRACK_SAVED_ORIGIN = 2
  PHASE_UNKNOWN = 0
  PHASE_WAIT_FAST_LIO = 1
  PHASE_WAIT_INS = 2
  PHASE_WAIT_MAP = 3
  PHASE_WAIT_GPS = 4
  PHASE_WAIT_ALIGNMENT = 5
  PHASE_READY_RTK = 6
  PHASE_READY_LIO_LOCKED = 7
  PHASE_READY_LIO_SEEDED = 8
  PHASE_READY_IMU_RESTRICTED = 9
  PHASE_SWITCHING_MAP = 10
  PHASE_RESTARTING_FUSION = 11
  PHASE_RESTARTING_ALL = 12
  PHASE_RECOVERING_LIO = 13
  PHASE_FAULT = 14
  PHASE_WAIT_IMU_ODOMETRY = 15
  PHASE_RESTART_VERIFYING = 16
  PHASE_WAIT_ALGORITHM = 17
  PHASE_WAIT_TRUSTED_OUTPUT = 18
  SOURCE_NONE = 0
  SOURCE_RTK = 1
  SOURCE_LIO_LOCKED = 2
  SOURCE_LIO_SEEDED = 3
  SOURCE_IMU_RESTRICTED = 4
  RESTART_NONE = 0
  RESTART_FUSION = 1
  RESTART_LIO = 2
  RESTART_ALL = 3
  FAULT_NONE = 0
  FAULT_MAP_INVALID = 1
  FAULT_RESTART_FAILED = 2
  FAULT_RESTART_SUPPRESSED = 3
  FAULT_POSITION_TIMEOUT = 4
  FAULT_LOW_FREQUENCY = 5
  FAULT_ALGORITHM = 6
  FAULT_RESTART_PARTIAL = 7

  __slots__ = ['header','reporter','requested_mode','active_mode','workflow_mode','requested_runtime_mode','active_runtime_mode','phase','position_source','position_state','position_valid','ins_status_received','ins_solution_good','ins_initialized','ins_status','ins_vehicle_align','ins_heading_flag','ins_position_status','fast_lio_initialized','fusion_generation_valid','fusion_generation_sec','fusion_generation_nsec','lio_generation_valid','lio_generation_sec','lio_generation_nsec','map_origin_ready','map_origin_committed','alignment_ready','alignment_locked','imu_odometry_ready','gps_good','lio_good','active_map','pending_map','last_created_map','active_map_uuid','pending_map_uuid','map_schema_version','coordinate_frame','origin_checksum','map_valid','algorithm_status_valid','transitioning','restart_in_progress','restart_scope','watchdog_position_timeout','watchdog_low_frequency','automatic_restart_suspended','automatic_restart_count','stop_required','fault_code','reason']
  _slot_types = ['std_msgs/Header','string','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint32','bool','bool','bool','bool','uint8','uint8','uint8','int32','bool','bool','uint32','uint32','bool','uint32','uint32','bool','bool','bool','bool','bool','bool','bool','string','string','string','string','string','uint32','string','string','bool','bool','bool','bool','uint8','bool','bool','bool','uint32','bool','uint16','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,reporter,requested_mode,active_mode,workflow_mode,requested_runtime_mode,active_runtime_mode,phase,position_source,position_state,position_valid,ins_status_received,ins_solution_good,ins_initialized,ins_status,ins_vehicle_align,ins_heading_flag,ins_position_status,fast_lio_initialized,fusion_generation_valid,fusion_generation_sec,fusion_generation_nsec,lio_generation_valid,lio_generation_sec,lio_generation_nsec,map_origin_ready,map_origin_committed,alignment_ready,alignment_locked,imu_odometry_ready,gps_good,lio_good,active_map,pending_map,last_created_map,active_map_uuid,pending_map_uuid,map_schema_version,coordinate_frame,origin_checksum,map_valid,algorithm_status_valid,transitioning,restart_in_progress,restart_scope,watchdog_position_timeout,watchdog_low_frequency,automatic_restart_suspended,automatic_restart_count,stop_required,fault_code,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocalizationStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.reporter is None:
        self.reporter = ''
      if self.requested_mode is None:
        self.requested_mode = 0
      if self.active_mode is None:
        self.active_mode = 0
      if self.workflow_mode is None:
        self.workflow_mode = 0
      if self.requested_runtime_mode is None:
        self.requested_runtime_mode = 0
      if self.active_runtime_mode is None:
        self.active_runtime_mode = 0
      if self.phase is None:
        self.phase = 0
      if self.position_source is None:
        self.position_source = 0
      if self.position_state is None:
        self.position_state = 0
      if self.position_valid is None:
        self.position_valid = False
      if self.ins_status_received is None:
        self.ins_status_received = False
      if self.ins_solution_good is None:
        self.ins_solution_good = False
      if self.ins_initialized is None:
        self.ins_initialized = False
      if self.ins_status is None:
        self.ins_status = 0
      if self.ins_vehicle_align is None:
        self.ins_vehicle_align = 0
      if self.ins_heading_flag is None:
        self.ins_heading_flag = 0
      if self.ins_position_status is None:
        self.ins_position_status = 0
      if self.fast_lio_initialized is None:
        self.fast_lio_initialized = False
      if self.fusion_generation_valid is None:
        self.fusion_generation_valid = False
      if self.fusion_generation_sec is None:
        self.fusion_generation_sec = 0
      if self.fusion_generation_nsec is None:
        self.fusion_generation_nsec = 0
      if self.lio_generation_valid is None:
        self.lio_generation_valid = False
      if self.lio_generation_sec is None:
        self.lio_generation_sec = 0
      if self.lio_generation_nsec is None:
        self.lio_generation_nsec = 0
      if self.map_origin_ready is None:
        self.map_origin_ready = False
      if self.map_origin_committed is None:
        self.map_origin_committed = False
      if self.alignment_ready is None:
        self.alignment_ready = False
      if self.alignment_locked is None:
        self.alignment_locked = False
      if self.imu_odometry_ready is None:
        self.imu_odometry_ready = False
      if self.gps_good is None:
        self.gps_good = False
      if self.lio_good is None:
        self.lio_good = False
      if self.active_map is None:
        self.active_map = ''
      if self.pending_map is None:
        self.pending_map = ''
      if self.last_created_map is None:
        self.last_created_map = ''
      if self.active_map_uuid is None:
        self.active_map_uuid = ''
      if self.pending_map_uuid is None:
        self.pending_map_uuid = ''
      if self.map_schema_version is None:
        self.map_schema_version = 0
      if self.coordinate_frame is None:
        self.coordinate_frame = ''
      if self.origin_checksum is None:
        self.origin_checksum = ''
      if self.map_valid is None:
        self.map_valid = False
      if self.algorithm_status_valid is None:
        self.algorithm_status_valid = False
      if self.transitioning is None:
        self.transitioning = False
      if self.restart_in_progress is None:
        self.restart_in_progress = False
      if self.restart_scope is None:
        self.restart_scope = 0
      if self.watchdog_position_timeout is None:
        self.watchdog_position_timeout = False
      if self.watchdog_low_frequency is None:
        self.watchdog_low_frequency = False
      if self.automatic_restart_suspended is None:
        self.automatic_restart_suspended = False
      if self.automatic_restart_count is None:
        self.automatic_restart_count = 0
      if self.stop_required is None:
        self.stop_required = False
      if self.fault_code is None:
        self.fault_code = 0
      if self.reason is None:
        self.reason = ''
    else:
      self.header = std_msgs.msg.Header()
      self.reporter = ''
      self.requested_mode = 0
      self.active_mode = 0
      self.workflow_mode = 0
      self.requested_runtime_mode = 0
      self.active_runtime_mode = 0
      self.phase = 0
      self.position_source = 0
      self.position_state = 0
      self.position_valid = False
      self.ins_status_received = False
      self.ins_solution_good = False
      self.ins_initialized = False
      self.ins_status = 0
      self.ins_vehicle_align = 0
      self.ins_heading_flag = 0
      self.ins_position_status = 0
      self.fast_lio_initialized = False
      self.fusion_generation_valid = False
      self.fusion_generation_sec = 0
      self.fusion_generation_nsec = 0
      self.lio_generation_valid = False
      self.lio_generation_sec = 0
      self.lio_generation_nsec = 0
      self.map_origin_ready = False
      self.map_origin_committed = False
      self.alignment_ready = False
      self.alignment_locked = False
      self.imu_odometry_ready = False
      self.gps_good = False
      self.lio_good = False
      self.active_map = ''
      self.pending_map = ''
      self.last_created_map = ''
      self.active_map_uuid = ''
      self.pending_map_uuid = ''
      self.map_schema_version = 0
      self.coordinate_frame = ''
      self.origin_checksum = ''
      self.map_valid = False
      self.algorithm_status_valid = False
      self.transitioning = False
      self.restart_in_progress = False
      self.restart_scope = 0
      self.watchdog_position_timeout = False
      self.watchdog_low_frequency = False
      self.automatic_restart_suspended = False
      self.automatic_restart_count = 0
      self.stop_required = False
      self.fault_code = 0
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.reporter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7BI7Bi2B2IB2I7B().pack(_x.requested_mode, _x.active_mode, _x.workflow_mode, _x.requested_runtime_mode, _x.active_runtime_mode, _x.phase, _x.position_source, _x.position_state, _x.position_valid, _x.ins_status_received, _x.ins_solution_good, _x.ins_initialized, _x.ins_status, _x.ins_vehicle_align, _x.ins_heading_flag, _x.ins_position_status, _x.fast_lio_initialized, _x.fusion_generation_valid, _x.fusion_generation_sec, _x.fusion_generation_nsec, _x.lio_generation_valid, _x.lio_generation_sec, _x.lio_generation_nsec, _x.map_origin_ready, _x.map_origin_committed, _x.alignment_ready, _x.alignment_locked, _x.imu_odometry_ready, _x.gps_good, _x.lio_good))
      _x = self.active_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pending_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.last_created_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.active_map_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pending_map_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.map_schema_version
      buff.write(_get_struct_I().pack(_x))
      _x = self.coordinate_frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.origin_checksum
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8BIBH().pack(_x.map_valid, _x.algorithm_status_valid, _x.transitioning, _x.restart_in_progress, _x.restart_scope, _x.watchdog_position_timeout, _x.watchdog_low_frequency, _x.automatic_restart_suspended, _x.automatic_restart_count, _x.stop_required, _x.fault_code))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reporter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reporter = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.requested_mode, _x.active_mode, _x.workflow_mode, _x.requested_runtime_mode, _x.active_runtime_mode, _x.phase, _x.position_source, _x.position_state, _x.position_valid, _x.ins_status_received, _x.ins_solution_good, _x.ins_initialized, _x.ins_status, _x.ins_vehicle_align, _x.ins_heading_flag, _x.ins_position_status, _x.fast_lio_initialized, _x.fusion_generation_valid, _x.fusion_generation_sec, _x.fusion_generation_nsec, _x.lio_generation_valid, _x.lio_generation_sec, _x.lio_generation_nsec, _x.map_origin_ready, _x.map_origin_committed, _x.alignment_ready, _x.alignment_locked, _x.imu_odometry_ready, _x.gps_good, _x.lio_good,) = _get_struct_7BI7Bi2B2IB2I7B().unpack(str[start:end])
      self.position_valid = bool(self.position_valid)
      self.ins_status_received = bool(self.ins_status_received)
      self.ins_solution_good = bool(self.ins_solution_good)
      self.ins_initialized = bool(self.ins_initialized)
      self.fast_lio_initialized = bool(self.fast_lio_initialized)
      self.fusion_generation_valid = bool(self.fusion_generation_valid)
      self.lio_generation_valid = bool(self.lio_generation_valid)
      self.map_origin_ready = bool(self.map_origin_ready)
      self.map_origin_committed = bool(self.map_origin_committed)
      self.alignment_ready = bool(self.alignment_ready)
      self.alignment_locked = bool(self.alignment_locked)
      self.imu_odometry_ready = bool(self.imu_odometry_ready)
      self.gps_good = bool(self.gps_good)
      self.lio_good = bool(self.lio_good)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pending_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pending_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_created_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_created_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_map_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_map_uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pending_map_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pending_map_uuid = str[start:end]
      start = end
      end += 4
      (self.map_schema_version,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.coordinate_frame = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.coordinate_frame = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.origin_checksum = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.origin_checksum = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.map_valid, _x.algorithm_status_valid, _x.transitioning, _x.restart_in_progress, _x.restart_scope, _x.watchdog_position_timeout, _x.watchdog_low_frequency, _x.automatic_restart_suspended, _x.automatic_restart_count, _x.stop_required, _x.fault_code,) = _get_struct_8BIBH().unpack(str[start:end])
      self.map_valid = bool(self.map_valid)
      self.algorithm_status_valid = bool(self.algorithm_status_valid)
      self.transitioning = bool(self.transitioning)
      self.restart_in_progress = bool(self.restart_in_progress)
      self.watchdog_position_timeout = bool(self.watchdog_position_timeout)
      self.watchdog_low_frequency = bool(self.watchdog_low_frequency)
      self.automatic_restart_suspended = bool(self.automatic_restart_suspended)
      self.stop_required = bool(self.stop_required)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.reporter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7BI7Bi2B2IB2I7B().pack(_x.requested_mode, _x.active_mode, _x.workflow_mode, _x.requested_runtime_mode, _x.active_runtime_mode, _x.phase, _x.position_source, _x.position_state, _x.position_valid, _x.ins_status_received, _x.ins_solution_good, _x.ins_initialized, _x.ins_status, _x.ins_vehicle_align, _x.ins_heading_flag, _x.ins_position_status, _x.fast_lio_initialized, _x.fusion_generation_valid, _x.fusion_generation_sec, _x.fusion_generation_nsec, _x.lio_generation_valid, _x.lio_generation_sec, _x.lio_generation_nsec, _x.map_origin_ready, _x.map_origin_committed, _x.alignment_ready, _x.alignment_locked, _x.imu_odometry_ready, _x.gps_good, _x.lio_good))
      _x = self.active_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pending_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.last_created_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.active_map_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pending_map_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.map_schema_version
      buff.write(_get_struct_I().pack(_x))
      _x = self.coordinate_frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.origin_checksum
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8BIBH().pack(_x.map_valid, _x.algorithm_status_valid, _x.transitioning, _x.restart_in_progress, _x.restart_scope, _x.watchdog_position_timeout, _x.watchdog_low_frequency, _x.automatic_restart_suspended, _x.automatic_restart_count, _x.stop_required, _x.fault_code))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reporter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reporter = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.requested_mode, _x.active_mode, _x.workflow_mode, _x.requested_runtime_mode, _x.active_runtime_mode, _x.phase, _x.position_source, _x.position_state, _x.position_valid, _x.ins_status_received, _x.ins_solution_good, _x.ins_initialized, _x.ins_status, _x.ins_vehicle_align, _x.ins_heading_flag, _x.ins_position_status, _x.fast_lio_initialized, _x.fusion_generation_valid, _x.fusion_generation_sec, _x.fusion_generation_nsec, _x.lio_generation_valid, _x.lio_generation_sec, _x.lio_generation_nsec, _x.map_origin_ready, _x.map_origin_committed, _x.alignment_ready, _x.alignment_locked, _x.imu_odometry_ready, _x.gps_good, _x.lio_good,) = _get_struct_7BI7Bi2B2IB2I7B().unpack(str[start:end])
      self.position_valid = bool(self.position_valid)
      self.ins_status_received = bool(self.ins_status_received)
      self.ins_solution_good = bool(self.ins_solution_good)
      self.ins_initialized = bool(self.ins_initialized)
      self.fast_lio_initialized = bool(self.fast_lio_initialized)
      self.fusion_generation_valid = bool(self.fusion_generation_valid)
      self.lio_generation_valid = bool(self.lio_generation_valid)
      self.map_origin_ready = bool(self.map_origin_ready)
      self.map_origin_committed = bool(self.map_origin_committed)
      self.alignment_ready = bool(self.alignment_ready)
      self.alignment_locked = bool(self.alignment_locked)
      self.imu_odometry_ready = bool(self.imu_odometry_ready)
      self.gps_good = bool(self.gps_good)
      self.lio_good = bool(self.lio_good)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pending_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pending_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_created_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_created_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_map_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_map_uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pending_map_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pending_map_uuid = str[start:end]
      start = end
      end += 4
      (self.map_schema_version,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.coordinate_frame = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.coordinate_frame = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.origin_checksum = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.origin_checksum = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.map_valid, _x.algorithm_status_valid, _x.transitioning, _x.restart_in_progress, _x.restart_scope, _x.watchdog_position_timeout, _x.watchdog_low_frequency, _x.automatic_restart_suspended, _x.automatic_restart_count, _x.stop_required, _x.fault_code,) = _get_struct_8BIBH().unpack(str[start:end])
      self.map_valid = bool(self.map_valid)
      self.algorithm_status_valid = bool(self.algorithm_status_valid)
      self.transitioning = bool(self.transitioning)
      self.restart_in_progress = bool(self.restart_in_progress)
      self.watchdog_position_timeout = bool(self.watchdog_position_timeout)
      self.watchdog_low_frequency = bool(self.watchdog_low_frequency)
      self.automatic_restart_suspended = bool(self.automatic_restart_suspended)
      self.stop_required = bool(self.stop_required)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7BI7Bi2B2IB2I7B = None
def _get_struct_7BI7Bi2B2IB2I7B():
    global _struct_7BI7Bi2B2IB2I7B
    if _struct_7BI7Bi2B2IB2I7B is None:
        _struct_7BI7Bi2B2IB2I7B = struct.Struct("<7BI7Bi2B2IB2I7B")
    return _struct_7BI7Bi2B2IB2I7B
_struct_8BIBH = None
def _get_struct_8BIBH():
    global _struct_8BIBH
    if _struct_8BIBH is None:
        _struct_8BIBH = struct.Struct("<8BIBH")
    return _struct_8BIBH
