# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from util/ManageLocalizationMapRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ManageLocalizationMapRequest(genpy.Message):
  _md5sum = "97835c85afd8e1d5520dfc73f4fbb216"
  _type = "util/ManageLocalizationMapRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Transactional map lifecycle API owned by fusion_4dof.
uint8 SAVE_CURRENT_AND_ACTIVATE=1
uint8 ACTIVATE_EXISTING=2

uint8 command
string map_name
bool overwrite
"""
  # Pseudo-constants
  SAVE_CURRENT_AND_ACTIVATE = 1
  ACTIVATE_EXISTING = 2

  __slots__ = ['command','map_name','overwrite']
  _slot_types = ['uint8','string','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       command,map_name,overwrite

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ManageLocalizationMapRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.command is None:
        self.command = 0
      if self.map_name is None:
        self.map_name = ''
      if self.overwrite is None:
        self.overwrite = False
    else:
      self.command = 0
      self.map_name = ''
      self.overwrite = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.command
      buff.write(_get_struct_B().pack(_x))
      _x = self.map_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.overwrite
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.command,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.map_name = str[start:end]
      start = end
      end += 1
      (self.overwrite,) = _get_struct_B().unpack(str[start:end])
      self.overwrite = bool(self.overwrite)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.command
      buff.write(_get_struct_B().pack(_x))
      _x = self.map_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.overwrite
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.command,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.map_name = str[start:end]
      start = end
      end += 1
      (self.overwrite,) = _get_struct_B().unpack(str[start:end])
      self.overwrite = bool(self.overwrite)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from util/ManageLocalizationMapResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ManageLocalizationMapResponse(genpy.Message):
  _md5sum = "839a6a6f72eca859c62078e8cacaeaf4"
  _type = "util/ManageLocalizationMapResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool success
bool alignment_preserved
bool switch_pending
string active_map
string active_map_uuid
string pending_map
string pending_map_uuid
uint32 map_schema_version
string coordinate_frame
string origin_checksum
string reason

"""
  __slots__ = ['success','alignment_preserved','switch_pending','active_map','active_map_uuid','pending_map','pending_map_uuid','map_schema_version','coordinate_frame','origin_checksum','reason']
  _slot_types = ['bool','bool','bool','string','string','string','string','uint32','string','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,alignment_preserved,switch_pending,active_map,active_map_uuid,pending_map,pending_map_uuid,map_schema_version,coordinate_frame,origin_checksum,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ManageLocalizationMapResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.alignment_preserved is None:
        self.alignment_preserved = False
      if self.switch_pending is None:
        self.switch_pending = False
      if self.active_map is None:
        self.active_map = ''
      if self.active_map_uuid is None:
        self.active_map_uuid = ''
      if self.pending_map is None:
        self.pending_map = ''
      if self.pending_map_uuid is None:
        self.pending_map_uuid = ''
      if self.map_schema_version is None:
        self.map_schema_version = 0
      if self.coordinate_frame is None:
        self.coordinate_frame = ''
      if self.origin_checksum is None:
        self.origin_checksum = ''
      if self.reason is None:
        self.reason = ''
    else:
      self.success = False
      self.alignment_preserved = False
      self.switch_pending = False
      self.active_map = ''
      self.active_map_uuid = ''
      self.pending_map = ''
      self.pending_map_uuid = ''
      self.map_schema_version = 0
      self.coordinate_frame = ''
      self.origin_checksum = ''
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.success, _x.alignment_preserved, _x.switch_pending))
      _x = self.active_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.active_map_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pending_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pending_map_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.map_schema_version
      buff.write(_get_struct_I().pack(_x))
      _x = self.coordinate_frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.origin_checksum
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.success, _x.alignment_preserved, _x.switch_pending,) = _get_struct_3B().unpack(str[start:end])
      self.success = bool(self.success)
      self.alignment_preserved = bool(self.alignment_preserved)
      self.switch_pending = bool(self.switch_pending)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_map_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_map_uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pending_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pending_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pending_map_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pending_map_uuid = str[start:end]
      start = end
      end += 4
      (self.map_schema_version,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.coordinate_frame = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.coordinate_frame = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.origin_checksum = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.origin_checksum = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.success, _x.alignment_preserved, _x.switch_pending))
      _x = self.active_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.active_map_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pending_map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pending_map_uuid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.map_schema_version
      buff.write(_get_struct_I().pack(_x))
      _x = self.coordinate_frame
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.origin_checksum
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.success, _x.alignment_preserved, _x.switch_pending,) = _get_struct_3B().unpack(str[start:end])
      self.success = bool(self.success)
      self.alignment_preserved = bool(self.alignment_preserved)
      self.switch_pending = bool(self.switch_pending)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_map_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_map_uuid = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pending_map = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pending_map = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pending_map_uuid = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pending_map_uuid = str[start:end]
      start = end
      end += 4
      (self.map_schema_version,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.coordinate_frame = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.coordinate_frame = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.origin_checksum = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.origin_checksum = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
class ManageLocalizationMap(object):
  _type          = 'util/ManageLocalizationMap'
  _md5sum = 'f6eb786c2817a22f906c5e66a8ae611a'
  _request_class  = ManageLocalizationMapRequest
  _response_class = ManageLocalizationMapResponse
