#relative position, m
float32 x1 # x_min
float32 y1 # y_min
float32 x2 # x_min
float32 y2 # y_max
float32 x3 # x_max
float32 y3 # y_max
float32 x4 # x_max
float32 y4 # y_min

# height, cm
float32 zmin

float32 zmax

# absolute speed, m/s
float32 speed

# deg
float32 speed_direction

uint32 id
string label

# center point coordinate in localpose frame, m
float32 global_x
float32 global_y

float32 local_x
float32 local_y