// Generated by gencpp from file mower_msgs/CamerargbState.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_CAMERARGBSTATE_H
#define MOWER_MSGS_MESSAGE_CAMERARGBSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct CamerargbState_
{
  typedef CamerargbState_<ContainerAllocator> Type;

  CamerargbState_()
    : is_camerargb_ok(false)  {
    }
  CamerargbState_(const ContainerAllocator& _alloc)
    : is_camerargb_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_camerargb_ok_type;
  _is_camerargb_ok_type is_camerargb_ok;





  typedef boost::shared_ptr< ::mower_msgs::CamerargbState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::CamerargbState_<ContainerAllocator> const> ConstPtr;

}; // struct CamerargbState_

typedef ::mower_msgs::CamerargbState_<std::allocator<void> > CamerargbState;

typedef boost::shared_ptr< ::mower_msgs::CamerargbState > CamerargbStatePtr;
typedef boost::shared_ptr< ::mower_msgs::CamerargbState const> CamerargbStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::CamerargbState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::CamerargbState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::CamerargbState_<ContainerAllocator1> & lhs, const ::mower_msgs::CamerargbState_<ContainerAllocator2> & rhs)
{
  return lhs.is_camerargb_ok == rhs.is_camerargb_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::CamerargbState_<ContainerAllocator1> & lhs, const ::mower_msgs::CamerargbState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::CamerargbState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::CamerargbState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::CamerargbState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::CamerargbState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::CamerargbState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::CamerargbState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::CamerargbState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8721ee57cc9045b375b087d6e5ab5399";
  }

  static const char* value(const ::mower_msgs::CamerargbState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8721ee57cc9045b3ULL;
  static const uint64_t static_value2 = 0x75b087d6e5ab5399ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::CamerargbState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/CamerargbState";
  }

  static const char* value(const ::mower_msgs::CamerargbState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::CamerargbState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_camerargb_ok\n"
;
  }

  static const char* value(const ::mower_msgs::CamerargbState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::CamerargbState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_camerargb_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CamerargbState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::CamerargbState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::CamerargbState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "is_camerargb_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_camerargb_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_CAMERARGBSTATE_H
