// Generated by gencpp from file mower_msgs/ControlState.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_CONTROLSTATE_H
#define MOWER_MSGS_MESSAGE_CONTROLSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mower_msgs
{
template <class ContainerAllocator>
struct ControlState_
{
  typedef ControlState_<ContainerAllocator> Type;

  ControlState_()
    : header()
    , control_state(0)  {
    }
  ControlState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control_state(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _control_state_type;
  _control_state_type control_state;





  typedef boost::shared_ptr< ::mower_msgs::ControlState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::ControlState_<ContainerAllocator> const> ConstPtr;

}; // struct ControlState_

typedef ::mower_msgs::ControlState_<std::allocator<void> > ControlState;

typedef boost::shared_ptr< ::mower_msgs::ControlState > ControlStatePtr;
typedef boost::shared_ptr< ::mower_msgs::ControlState const> ControlStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::ControlState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::ControlState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::ControlState_<ContainerAllocator1> & lhs, const ::mower_msgs::ControlState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.control_state == rhs.control_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::ControlState_<ContainerAllocator1> & lhs, const ::mower_msgs::ControlState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::ControlState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::ControlState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::ControlState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::ControlState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::ControlState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::ControlState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15251f5c1c2c764e6732e712efff289a";
  }

  static const char* value(const ::mower_msgs::ControlState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15251f5c1c2c764eULL;
  static const uint64_t static_value2 = 0x6732e712efff289aULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/ControlState";
  }

  static const char* value(const ::mower_msgs::ControlState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint8 control_state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mower_msgs::ControlState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::ControlState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::ControlState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::ControlState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "control_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_CONTROLSTATE_H
