// Generated by gencpp from file mower_msgs/ControlOk.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_CONTROLOK_H
#define MOWER_MSGS_MESSAGE_CONTROLOK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mower_msgs
{
template <class ContainerAllocator>
struct ControlOk_
{
  typedef ControlOk_<ContainerAllocator> Type;

  ControlOk_()
    : header()
    , is_control_ok(false)
    , finished(false)  {
    }
  ControlOk_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_control_ok(false)
    , finished(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_control_ok_type;
  _is_control_ok_type is_control_ok;

   typedef uint8_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::mower_msgs::ControlOk_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::ControlOk_<ContainerAllocator> const> ConstPtr;

}; // struct ControlOk_

typedef ::mower_msgs::ControlOk_<std::allocator<void> > ControlOk;

typedef boost::shared_ptr< ::mower_msgs::ControlOk > ControlOkPtr;
typedef boost::shared_ptr< ::mower_msgs::ControlOk const> ControlOkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::ControlOk_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::ControlOk_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::ControlOk_<ContainerAllocator1> & lhs, const ::mower_msgs::ControlOk_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.is_control_ok == rhs.is_control_ok &&
    lhs.finished == rhs.finished;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::ControlOk_<ContainerAllocator1> & lhs, const ::mower_msgs::ControlOk_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::ControlOk_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::ControlOk_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::ControlOk_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::ControlOk_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::ControlOk_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::ControlOk_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::ControlOk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1b519c21944b4cf1e0569f6c2cb3a72";
  }

  static const char* value(const ::mower_msgs::ControlOk_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1b519c21944b4cfULL;
  static const uint64_t static_value2 = 0x1e0569f6c2cb3a72ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::ControlOk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/ControlOk";
  }

  static const char* value(const ::mower_msgs::ControlOk_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::ControlOk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"\n"
"bool is_control_ok\n"
"bool finished\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mower_msgs::ControlOk_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::ControlOk_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_control_ok);
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlOk_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::ControlOk_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::ControlOk_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_control_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_control_ok);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_CONTROLOK_H
