// Generated by gencpp from file mower_msgs/Direct_Control.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_DIRECT_CONTROL_H
#define MOWER_MSGS_MESSAGE_DIRECT_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct Direct_Control_
{
  typedef Direct_Control_<ContainerAllocator> Type;

  Direct_Control_()
    : drive_mode(0)
    , speed_max(0.0)
    , mow_height(0)  {
    }
  Direct_Control_(const ContainerAllocator& _alloc)
    : drive_mode(0)
    , speed_max(0.0)
    , mow_height(0)  {
  (void)_alloc;
    }



   typedef uint8_t _drive_mode_type;
  _drive_mode_type drive_mode;

   typedef double _speed_max_type;
  _speed_max_type speed_max;

   typedef uint8_t _mow_height_type;
  _mow_height_type mow_height;





  typedef boost::shared_ptr< ::mower_msgs::Direct_Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::Direct_Control_<ContainerAllocator> const> ConstPtr;

}; // struct Direct_Control_

typedef ::mower_msgs::Direct_Control_<std::allocator<void> > Direct_Control;

typedef boost::shared_ptr< ::mower_msgs::Direct_Control > Direct_ControlPtr;
typedef boost::shared_ptr< ::mower_msgs::Direct_Control const> Direct_ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::Direct_Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::Direct_Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::Direct_Control_<ContainerAllocator1> & lhs, const ::mower_msgs::Direct_Control_<ContainerAllocator2> & rhs)
{
  return lhs.drive_mode == rhs.drive_mode &&
    lhs.speed_max == rhs.speed_max &&
    lhs.mow_height == rhs.mow_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::Direct_Control_<ContainerAllocator1> & lhs, const ::mower_msgs::Direct_Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Direct_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Direct_Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Direct_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Direct_Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Direct_Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Direct_Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::Direct_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10579a0a02d1c1d2b089c0bf3df04393";
  }

  static const char* value(const ::mower_msgs::Direct_Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10579a0a02d1c1d2ULL;
  static const uint64_t static_value2 = 0xb089c0bf3df04393ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::Direct_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/Direct_Control";
  }

  static const char* value(const ::mower_msgs::Direct_Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::Direct_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 drive_mode\n"
"float64 speed_max\n"
"uint8 mow_height\n"
;
  }

  static const char* value(const ::mower_msgs::Direct_Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::Direct_Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drive_mode);
      stream.next(m.speed_max);
      stream.next(m.mow_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Direct_Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::Direct_Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::Direct_Control_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "drive_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.drive_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed_max: ";
    Printer<double>::stream(s, indent + "  ", v.speed_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mow_height: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mow_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_DIRECT_CONTROL_H
