// Generated by gencpp from file mower_msgs/Fault_Code.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_FAULT_CODE_H
#define MOWER_MSGS_MESSAGE_FAULT_CODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct Fault_Code_
{
  typedef Fault_Code_<ContainerAllocator> Type;

  Fault_Code_()
    : fault_code()  {
    }
  Fault_Code_(const ContainerAllocator& _alloc)
    : fault_code()  {
      fault_code.assign(std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>(_alloc));
  }



   typedef boost::array<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, 13>  _fault_code_type;
  _fault_code_type fault_code;





  typedef boost::shared_ptr< ::mower_msgs::Fault_Code_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::Fault_Code_<ContainerAllocator> const> ConstPtr;

}; // struct Fault_Code_

typedef ::mower_msgs::Fault_Code_<std::allocator<void> > Fault_Code;

typedef boost::shared_ptr< ::mower_msgs::Fault_Code > Fault_CodePtr;
typedef boost::shared_ptr< ::mower_msgs::Fault_Code const> Fault_CodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::Fault_Code_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::Fault_Code_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::Fault_Code_<ContainerAllocator1> & lhs, const ::mower_msgs::Fault_Code_<ContainerAllocator2> & rhs)
{
  return lhs.fault_code == rhs.fault_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::Fault_Code_<ContainerAllocator1> & lhs, const ::mower_msgs::Fault_Code_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Fault_Code_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Fault_Code_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Fault_Code_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Fault_Code_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Fault_Code_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Fault_Code_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::Fault_Code_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42556c67ec9fdf90479d909abb5c32a1";
  }

  static const char* value(const ::mower_msgs::Fault_Code_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42556c67ec9fdf90ULL;
  static const uint64_t static_value2 = 0x479d909abb5c32a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::Fault_Code_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/Fault_Code";
  }

  static const char* value(const ::mower_msgs::Fault_Code_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::Fault_Code_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[13] fault_code\n"
"\n"
;
  }

  static const char* value(const ::mower_msgs::Fault_Code_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::Fault_Code_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fault_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Fault_Code_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::Fault_Code_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::Fault_Code_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "fault_code: ";
    if (v.fault_code.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.fault_code.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.fault_code[i]);
    }
    if (v.fault_code.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_FAULT_CODE_H
