// Generated by gencpp from file mower_msgs/Intervene.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_INTERVENE_H
#define MOWER_MSGS_MESSAGE_INTERVENE_H

#include <ros/service_traits.h>


#include <mower_msgs/InterveneRequest.h>
#include <mower_msgs/InterveneResponse.h>


namespace mower_msgs
{

struct Intervene
{

typedef InterveneRequest Request;
typedef InterveneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Intervene
} // namespace mower_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mower_msgs::Intervene > {
  static const char* value()
  {
    return "15f1f9695525704904993d3c41cc8ed1";
  }

  static const char* value(const ::mower_msgs::Intervene&) { return value(); }
};

template<>
struct DataType< ::mower_msgs::Intervene > {
  static const char* value()
  {
    return "mower_msgs/Intervene";
  }

  static const char* value(const ::mower_msgs::Intervene&) { return value(); }
};


// service_traits::MD5Sum< ::mower_msgs::InterveneRequest> should match
// service_traits::MD5Sum< ::mower_msgs::Intervene >
template<>
struct MD5Sum< ::mower_msgs::InterveneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mower_msgs::Intervene >::value();
  }
  static const char* value(const ::mower_msgs::InterveneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mower_msgs::InterveneRequest> should match
// service_traits::DataType< ::mower_msgs::Intervene >
template<>
struct DataType< ::mower_msgs::InterveneRequest>
{
  static const char* value()
  {
    return DataType< ::mower_msgs::Intervene >::value();
  }
  static const char* value(const ::mower_msgs::InterveneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mower_msgs::InterveneResponse> should match
// service_traits::MD5Sum< ::mower_msgs::Intervene >
template<>
struct MD5Sum< ::mower_msgs::InterveneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mower_msgs::Intervene >::value();
  }
  static const char* value(const ::mower_msgs::InterveneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mower_msgs::InterveneResponse> should match
// service_traits::DataType< ::mower_msgs::Intervene >
template<>
struct DataType< ::mower_msgs::InterveneResponse>
{
  static const char* value()
  {
    return DataType< ::mower_msgs::Intervene >::value();
  }
  static const char* value(const ::mower_msgs::InterveneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_INTERVENE_H
