// Generated by gencpp from file mower_msgs/InterveneResponse.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_INTERVENERESPONSE_H
#define MOWER_MSGS_MESSAGE_INTERVENERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct InterveneResponse_
{
  typedef InterveneResponse_<ContainerAllocator> Type;

  InterveneResponse_()
    : node_event(0)  {
    }
  InterveneResponse_(const ContainerAllocator& _alloc)
    : node_event(0)  {
  (void)_alloc;
    }



   typedef int32_t _node_event_type;
  _node_event_type node_event;





  typedef boost::shared_ptr< ::mower_msgs::InterveneResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::InterveneResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InterveneResponse_

typedef ::mower_msgs::InterveneResponse_<std::allocator<void> > InterveneResponse;

typedef boost::shared_ptr< ::mower_msgs::InterveneResponse > InterveneResponsePtr;
typedef boost::shared_ptr< ::mower_msgs::InterveneResponse const> InterveneResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::InterveneResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::InterveneResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::InterveneResponse_<ContainerAllocator1> & lhs, const ::mower_msgs::InterveneResponse_<ContainerAllocator2> & rhs)
{
  return lhs.node_event == rhs.node_event;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::InterveneResponse_<ContainerAllocator1> & lhs, const ::mower_msgs::InterveneResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::InterveneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::InterveneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::InterveneResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::InterveneResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::InterveneResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::InterveneResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::InterveneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2e1c3ce22be5a404a01a0373710b326";
  }

  static const char* value(const ::mower_msgs::InterveneResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2e1c3ce22be5a40ULL;
  static const uint64_t static_value2 = 0x4a01a0373710b326ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::InterveneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/InterveneResponse";
  }

  static const char* value(const ::mower_msgs::InterveneResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::InterveneResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32  node_event\n"
"\n"
;
  }

  static const char* value(const ::mower_msgs::InterveneResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::InterveneResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node_event);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterveneResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::InterveneResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::InterveneResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "node_event: ";
    Printer<int32_t>::stream(s, indent + "  ", v.node_event);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_INTERVENERESPONSE_H
