// Generated by gencpp from file mower_msgs/LidarSelfDtect.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_LIDARSELFDTECT_H
#define MOWER_MSGS_MESSAGE_LIDARSELFDTECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct LidarSelfDtect_
{
  typedef LidarSelfDtect_<ContainerAllocator> Type;

  LidarSelfDtect_()
    : is_lidar_ok(false)  {
    }
  LidarSelfDtect_(const ContainerAllocator& _alloc)
    : is_lidar_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_lidar_ok_type;
  _is_lidar_ok_type is_lidar_ok;





  typedef boost::shared_ptr< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> const> ConstPtr;

}; // struct LidarSelfDtect_

typedef ::mower_msgs::LidarSelfDtect_<std::allocator<void> > LidarSelfDtect;

typedef boost::shared_ptr< ::mower_msgs::LidarSelfDtect > LidarSelfDtectPtr;
typedef boost::shared_ptr< ::mower_msgs::LidarSelfDtect const> LidarSelfDtectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::LidarSelfDtect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::LidarSelfDtect_<ContainerAllocator1> & lhs, const ::mower_msgs::LidarSelfDtect_<ContainerAllocator2> & rhs)
{
  return lhs.is_lidar_ok == rhs.is_lidar_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::LidarSelfDtect_<ContainerAllocator1> & lhs, const ::mower_msgs::LidarSelfDtect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61b1182e9e63e0b66c126403f70148e4";
  }

  static const char* value(const ::mower_msgs::LidarSelfDtect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61b1182e9e63e0b6ULL;
  static const uint64_t static_value2 = 0x6c126403f70148e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/LidarSelfDtect";
  }

  static const char* value(const ::mower_msgs::LidarSelfDtect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_lidar_ok\n"
;
  }

  static const char* value(const ::mower_msgs::LidarSelfDtect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_lidar_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarSelfDtect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::LidarSelfDtect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::LidarSelfDtect_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "is_lidar_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_lidar_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_LIDARSELFDTECT_H
