// Generated by gencpp from file mower_msgs/Manual_Driving_Cmd.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_MANUAL_DRIVING_CMD_H
#define MOWER_MSGS_MESSAGE_MANUAL_DRIVING_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct Manual_Driving_Cmd_
{
  typedef Manual_Driving_Cmd_<ContainerAllocator> Type;

  Manual_Driving_Cmd_()
    : ad_control_enable(0)
    , turn_value(0)
    , drive_value(0)
    , gear_model(0)
    , mover_bool(0)
    , mow_height(0)  {
    }
  Manual_Driving_Cmd_(const ContainerAllocator& _alloc)
    : ad_control_enable(0)
    , turn_value(0)
    , drive_value(0)
    , gear_model(0)
    , mover_bool(0)
    , mow_height(0)  {
  (void)_alloc;
    }



   typedef uint8_t _ad_control_enable_type;
  _ad_control_enable_type ad_control_enable;

   typedef uint16_t _turn_value_type;
  _turn_value_type turn_value;

   typedef uint16_t _drive_value_type;
  _drive_value_type drive_value;

   typedef uint8_t _gear_model_type;
  _gear_model_type gear_model;

   typedef uint8_t _mover_bool_type;
  _mover_bool_type mover_bool;

   typedef uint8_t _mow_height_type;
  _mow_height_type mow_height;





  typedef boost::shared_ptr< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> const> ConstPtr;

}; // struct Manual_Driving_Cmd_

typedef ::mower_msgs::Manual_Driving_Cmd_<std::allocator<void> > Manual_Driving_Cmd;

typedef boost::shared_ptr< ::mower_msgs::Manual_Driving_Cmd > Manual_Driving_CmdPtr;
typedef boost::shared_ptr< ::mower_msgs::Manual_Driving_Cmd const> Manual_Driving_CmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator1> & lhs, const ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator2> & rhs)
{
  return lhs.ad_control_enable == rhs.ad_control_enable &&
    lhs.turn_value == rhs.turn_value &&
    lhs.drive_value == rhs.drive_value &&
    lhs.gear_model == rhs.gear_model &&
    lhs.mover_bool == rhs.mover_bool &&
    lhs.mow_height == rhs.mow_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator1> & lhs, const ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2904fb773f7150886bc5690b6fc3e977";
  }

  static const char* value(const ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2904fb773f715088ULL;
  static const uint64_t static_value2 = 0x6bc5690b6fc3e977ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/Manual_Driving_Cmd";
  }

  static const char* value(const ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Manual_Driving_Cmd\n"
"uint8 ad_control_enable\n"
"uint16 turn_value\n"
"uint16 drive_value\n"
"uint8 gear_model\n"
"uint8 mover_bool\n"
"uint8 mow_height\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ad_control_enable);
      stream.next(m.turn_value);
      stream.next(m.drive_value);
      stream.next(m.gear_model);
      stream.next(m.mover_bool);
      stream.next(m.mow_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Manual_Driving_Cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::Manual_Driving_Cmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ad_control_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ad_control_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "turn_value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.turn_value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "drive_value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.drive_value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gear_model: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_model);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mover_bool: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mover_bool);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mow_height: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mow_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_MANUAL_DRIVING_CMD_H
