// Generated by gencpp from file mower_msgs/Monitor.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_MONITOR_H
#define MOWER_MSGS_MESSAGE_MONITOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct Monitor_
{
  typedef Monitor_<ContainerAllocator> Type;

  Monitor_()
    : node_normal()  {
      node_normal.assign(false);
  }
  Monitor_(const ContainerAllocator& _alloc)
    : node_normal()  {
  (void)_alloc;
      node_normal.assign(false);
  }



   typedef boost::array<uint8_t, 13>  _node_normal_type;
  _node_normal_type node_normal;





  typedef boost::shared_ptr< ::mower_msgs::Monitor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::Monitor_<ContainerAllocator> const> ConstPtr;

}; // struct Monitor_

typedef ::mower_msgs::Monitor_<std::allocator<void> > Monitor;

typedef boost::shared_ptr< ::mower_msgs::Monitor > MonitorPtr;
typedef boost::shared_ptr< ::mower_msgs::Monitor const> MonitorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::Monitor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::Monitor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::Monitor_<ContainerAllocator1> & lhs, const ::mower_msgs::Monitor_<ContainerAllocator2> & rhs)
{
  return lhs.node_normal == rhs.node_normal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::Monitor_<ContainerAllocator1> & lhs, const ::mower_msgs::Monitor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Monitor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Monitor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Monitor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Monitor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Monitor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Monitor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::Monitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fa716a375e1d424b9eff8c8c0b57ef5";
  }

  static const char* value(const ::mower_msgs::Monitor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fa716a375e1d424ULL;
  static const uint64_t static_value2 = 0xb9eff8c8c0b57ef5ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::Monitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/Monitor";
  }

  static const char* value(const ::mower_msgs::Monitor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::Monitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[13] node_normal\n"
"\n"
;
  }

  static const char* value(const ::mower_msgs::Monitor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::Monitor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node_normal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Monitor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::Monitor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::Monitor_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "node_normal: ";
    if (v.node_normal.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.node_normal.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.node_normal[i]);
    }
    if (v.node_normal.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_MONITOR_H
