// Generated by gencpp from file mower_msgs/MultiMapSelfDetect.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_MULTIMAPSELFDETECT_H
#define MOWER_MSGS_MESSAGE_MULTIMAPSELFDETECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct MultiMapSelfDetect_
{
  typedef MultiMapSelfDetect_<ContainerAllocator> Type;

  MultiMapSelfDetect_()
    : is_multi_map_ok(false)  {
    }
  MultiMapSelfDetect_(const ContainerAllocator& _alloc)
    : is_multi_map_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_multi_map_ok_type;
  _is_multi_map_ok_type is_multi_map_ok;





  typedef boost::shared_ptr< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> const> ConstPtr;

}; // struct MultiMapSelfDetect_

typedef ::mower_msgs::MultiMapSelfDetect_<std::allocator<void> > MultiMapSelfDetect;

typedef boost::shared_ptr< ::mower_msgs::MultiMapSelfDetect > MultiMapSelfDetectPtr;
typedef boost::shared_ptr< ::mower_msgs::MultiMapSelfDetect const> MultiMapSelfDetectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator1> & lhs, const ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator2> & rhs)
{
  return lhs.is_multi_map_ok == rhs.is_multi_map_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator1> & lhs, const ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31d7c6c31bbf8db62e247ca761103d55";
  }

  static const char* value(const ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31d7c6c31bbf8db6ULL;
  static const uint64_t static_value2 = 0x2e247ca761103d55ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/MultiMapSelfDetect";
  }

  static const char* value(const ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_multi_map_ok\n"
;
  }

  static const char* value(const ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_multi_map_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiMapSelfDetect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::MultiMapSelfDetect_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "is_multi_map_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_multi_map_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_MULTIMAPSELFDETECT_H
