// Generated by gencpp from file mower_msgs/PlanType.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_PLANTYPE_H
#define MOWER_MSGS_MESSAGE_PLANTYPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct PlanType_
{
  typedef PlanType_<ContainerAllocator> Type;

  PlanType_()
    : plan_type_state(0)  {
    }
  PlanType_(const ContainerAllocator& _alloc)
    : plan_type_state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _plan_type_state_type;
  _plan_type_state_type plan_type_state;





  typedef boost::shared_ptr< ::mower_msgs::PlanType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::PlanType_<ContainerAllocator> const> ConstPtr;

}; // struct PlanType_

typedef ::mower_msgs::PlanType_<std::allocator<void> > PlanType;

typedef boost::shared_ptr< ::mower_msgs::PlanType > PlanTypePtr;
typedef boost::shared_ptr< ::mower_msgs::PlanType const> PlanTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::PlanType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::PlanType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::PlanType_<ContainerAllocator1> & lhs, const ::mower_msgs::PlanType_<ContainerAllocator2> & rhs)
{
  return lhs.plan_type_state == rhs.plan_type_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::PlanType_<ContainerAllocator1> & lhs, const ::mower_msgs::PlanType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::PlanType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::PlanType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::PlanType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::PlanType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::PlanType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::PlanType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::PlanType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23d6dde9eb5a6d1df00bc1332e5a8aeb";
  }

  static const char* value(const ::mower_msgs::PlanType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23d6dde9eb5a6d1dULL;
  static const uint64_t static_value2 = 0xf00bc1332e5a8aebULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::PlanType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/PlanType";
  }

  static const char* value(const ::mower_msgs::PlanType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::PlanType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 plan_type_state\n"
;
  }

  static const char* value(const ::mower_msgs::PlanType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::PlanType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan_type_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::PlanType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::PlanType_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "plan_type_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_type_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_PLANTYPE_H
