// Generated by gencpp from file mower_msgs/SegState.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_SEGSTATE_H
#define MOWER_MSGS_MESSAGE_SEGSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct SegState_
{
  typedef SegState_<ContainerAllocator> Type;

  SegState_()
    : is_seg_ok(false)  {
    }
  SegState_(const ContainerAllocator& _alloc)
    : is_seg_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_seg_ok_type;
  _is_seg_ok_type is_seg_ok;





  typedef boost::shared_ptr< ::mower_msgs::SegState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::SegState_<ContainerAllocator> const> ConstPtr;

}; // struct SegState_

typedef ::mower_msgs::SegState_<std::allocator<void> > SegState;

typedef boost::shared_ptr< ::mower_msgs::SegState > SegStatePtr;
typedef boost::shared_ptr< ::mower_msgs::SegState const> SegStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::SegState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::SegState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::SegState_<ContainerAllocator1> & lhs, const ::mower_msgs::SegState_<ContainerAllocator2> & rhs)
{
  return lhs.is_seg_ok == rhs.is_seg_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::SegState_<ContainerAllocator1> & lhs, const ::mower_msgs::SegState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::SegState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::SegState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::SegState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::SegState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::SegState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::SegState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::SegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a12252519f1037241c6783756d61d0f";
  }

  static const char* value(const ::mower_msgs::SegState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a12252519f10372ULL;
  static const uint64_t static_value2 = 0x41c6783756d61d0fULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::SegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/SegState";
  }

  static const char* value(const ::mower_msgs::SegState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::SegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_seg_ok\n"
;
  }

  static const char* value(const ::mower_msgs::SegState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::SegState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_seg_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SegState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::SegState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::SegState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "is_seg_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_seg_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_SEGSTATE_H
