// Generated by gencpp from file mower_msgs/TaskStatus.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_TASKSTATUS_H
#define MOWER_MSGS_MESSAGE_TASKSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct TaskStatus_
{
  typedef TaskStatus_<ContainerAllocator> Type;

  TaskStatus_()
    : task_status()  {
    }
  TaskStatus_(const ContainerAllocator& _alloc)
    : task_status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_status_type;
  _task_status_type task_status;





  typedef boost::shared_ptr< ::mower_msgs::TaskStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::TaskStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TaskStatus_

typedef ::mower_msgs::TaskStatus_<std::allocator<void> > TaskStatus;

typedef boost::shared_ptr< ::mower_msgs::TaskStatus > TaskStatusPtr;
typedef boost::shared_ptr< ::mower_msgs::TaskStatus const> TaskStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::TaskStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::TaskStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::TaskStatus_<ContainerAllocator1> & lhs, const ::mower_msgs::TaskStatus_<ContainerAllocator2> & rhs)
{
  return lhs.task_status == rhs.task_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::TaskStatus_<ContainerAllocator1> & lhs, const ::mower_msgs::TaskStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::TaskStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::TaskStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::TaskStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::TaskStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::TaskStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::TaskStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53109e0b2984975887b08ba65c603762";
  }

  static const char* value(const ::mower_msgs::TaskStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53109e0b29849758ULL;
  static const uint64_t static_value2 = 0x87b08ba65c603762ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/TaskStatus";
  }

  static const char* value(const ::mower_msgs::TaskStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task_status\n"
"\n"
;
  }

  static const char* value(const ::mower_msgs::TaskStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::TaskStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::TaskStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::TaskStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "task_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_TASKSTATUS_H
