// Generated by gencpp from file mower_msgs/TimeAreaLeft.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_TIMEAREALEFT_H
#define MOWER_MSGS_MESSAGE_TIMEAREALEFT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct TimeAreaLeft_
{
  typedef TimeAreaLeft_<ContainerAllocator> Type;

  TimeAreaLeft_()
    : time_left(0.0)
    , area_left(0.0)  {
    }
  TimeAreaLeft_(const ContainerAllocator& _alloc)
    : time_left(0.0)
    , area_left(0.0)  {
  (void)_alloc;
    }



   typedef double _time_left_type;
  _time_left_type time_left;

   typedef double _area_left_type;
  _area_left_type area_left;





  typedef boost::shared_ptr< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> const> ConstPtr;

}; // struct TimeAreaLeft_

typedef ::mower_msgs::TimeAreaLeft_<std::allocator<void> > TimeAreaLeft;

typedef boost::shared_ptr< ::mower_msgs::TimeAreaLeft > TimeAreaLeftPtr;
typedef boost::shared_ptr< ::mower_msgs::TimeAreaLeft const> TimeAreaLeftConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::TimeAreaLeft_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::TimeAreaLeft_<ContainerAllocator1> & lhs, const ::mower_msgs::TimeAreaLeft_<ContainerAllocator2> & rhs)
{
  return lhs.time_left == rhs.time_left &&
    lhs.area_left == rhs.area_left;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::TimeAreaLeft_<ContainerAllocator1> & lhs, const ::mower_msgs::TimeAreaLeft_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3450601933b56d4bc50d61223a1754f6";
  }

  static const char* value(const ::mower_msgs::TimeAreaLeft_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3450601933b56d4bULL;
  static const uint64_t static_value2 = 0xc50d61223a1754f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/TimeAreaLeft";
  }

  static const char* value(const ::mower_msgs::TimeAreaLeft_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time_left\n"
"float64 area_left\n"
;
  }

  static const char* value(const ::mower_msgs::TimeAreaLeft_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_left);
      stream.next(m.area_left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeAreaLeft_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::TimeAreaLeft_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::TimeAreaLeft_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "time_left: ";
    Printer<double>::stream(s, indent + "  ", v.time_left);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "area_left: ";
    Printer<double>::stream(s, indent + "  ", v.area_left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_TIMEAREALEFT_H
