// Generated by gencpp from file mower_msgs/VehicleInfo.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_VEHICLEINFO_H
#define MOWER_MSGS_MESSAGE_VEHICLEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mower_msgs
{
template <class ContainerAllocator>
struct VehicleInfo_
{
  typedef VehicleInfo_<ContainerAllocator> Type;

  VehicleInfo_()
    : header()
    , speed_status(0.0)
    , leftw_speed(0.0)
    , rightw_speed(0.0)
    , gear_model(0)
    , drive_mode(0)
    , mow_height(0)
    , battery_soc(0)  {
    }
  VehicleInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed_status(0.0)
    , leftw_speed(0.0)
    , rightw_speed(0.0)
    , gear_model(0)
    , drive_mode(0)
    , mow_height(0)
    , battery_soc(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _speed_status_type;
  _speed_status_type speed_status;

   typedef double _leftw_speed_type;
  _leftw_speed_type leftw_speed;

   typedef double _rightw_speed_type;
  _rightw_speed_type rightw_speed;

   typedef uint8_t _gear_model_type;
  _gear_model_type gear_model;

   typedef uint8_t _drive_mode_type;
  _drive_mode_type drive_mode;

   typedef uint8_t _mow_height_type;
  _mow_height_type mow_height;

   typedef uint8_t _battery_soc_type;
  _battery_soc_type battery_soc;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(P_Gear)
  #undef P_Gear
#endif
#if defined(_WIN32) && defined(R_Gear)
  #undef R_Gear
#endif
#if defined(_WIN32) && defined(N_Gear)
  #undef N_Gear
#endif
#if defined(_WIN32) && defined(D_Gear)
  #undef D_Gear
#endif
#if defined(_WIN32) && defined(Manualcontrol_mode)
  #undef Manualcontrol_mode
#endif
#if defined(_WIN32) && defined(Automaticcontrol_mode)
  #undef Automaticcontrol_mode
#endif
#if defined(_WIN32) && defined(Remotecontrol_mode)
  #undef Remotecontrol_mode
#endif
#if defined(_WIN32) && defined(Low_mode)
  #undef Low_mode
#endif
#if defined(_WIN32) && defined(Medium_mode)
  #undef Medium_mode
#endif
#if defined(_WIN32) && defined(High_mode)
  #undef High_mode
#endif

  enum {
    P_Gear = 0u,
    R_Gear = 1u,
    N_Gear = 2u,
    D_Gear = 3u,
    Manualcontrol_mode = 0u,
    Automaticcontrol_mode = 1u,
    Remotecontrol_mode = 2u,
    Low_mode = 2u,
    Medium_mode = 1u,
    High_mode = 0u,
  };


  typedef boost::shared_ptr< ::mower_msgs::VehicleInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::VehicleInfo_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleInfo_

typedef ::mower_msgs::VehicleInfo_<std::allocator<void> > VehicleInfo;

typedef boost::shared_ptr< ::mower_msgs::VehicleInfo > VehicleInfoPtr;
typedef boost::shared_ptr< ::mower_msgs::VehicleInfo const> VehicleInfoConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::VehicleInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::VehicleInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::VehicleInfo_<ContainerAllocator1> & lhs, const ::mower_msgs::VehicleInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.speed_status == rhs.speed_status &&
    lhs.leftw_speed == rhs.leftw_speed &&
    lhs.rightw_speed == rhs.rightw_speed &&
    lhs.gear_model == rhs.gear_model &&
    lhs.drive_mode == rhs.drive_mode &&
    lhs.mow_height == rhs.mow_height &&
    lhs.battery_soc == rhs.battery_soc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::VehicleInfo_<ContainerAllocator1> & lhs, const ::mower_msgs::VehicleInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::VehicleInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::VehicleInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::VehicleInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::VehicleInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::VehicleInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::VehicleInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::VehicleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a2a4b2a095bc9355e18d7be4b50f3fd";
  }

  static const char* value(const ::mower_msgs::VehicleInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a2a4b2a095bc935ULL;
  static const uint64_t static_value2 = 0x5e18d7be4b50f3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::VehicleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/VehicleInfo";
  }

  static const char* value(const ::mower_msgs::VehicleInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::VehicleInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# AGVStatus 0x301  现履带车底控无反馈，均不成立\n"
"float64 speed_status  \n"
"float64 leftw_speed   \n"
"float64 rightw_speed\n"
"uint8 gear_model      \n"
"uint8 drive_mode\n"
"uint8 mow_height\n"
"uint8 battery_soc\n"
"\n"
"#gear_model\n"
"uint8 P_Gear=0 # 0x00： P 档\n"
"uint8 R_Gear=1 # 0x01： 倒档R\n"
"uint8 N_Gear=2 # 0x02： N 档\n"
"uint8 D_Gear=3 # 0x03： D 档\n"
"#drive_model\n"
"uint8 Manualcontrol_mode=0 # 0x00：手动控制模式\n"
"uint8 Automaticcontrol_mode=1 # 0x01：自动控制模式\n"
"uint8 Remotecontrol_mode=2 # 0x02：遥控器调试模式\n"
"#mow_height\n"
"uint8 Low_mode=2 # 0x02：割草高度为低\n"
"uint8 Medium_mode=1 # 0x01：割草高度为中\n"
"uint8 High_mode=0 # 0x00：割草高度为高\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mower_msgs::VehicleInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::VehicleInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed_status);
      stream.next(m.leftw_speed);
      stream.next(m.rightw_speed);
      stream.next(m.gear_model);
      stream.next(m.drive_mode);
      stream.next(m.mow_height);
      stream.next(m.battery_soc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::VehicleInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::VehicleInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed_status: ";
    Printer<double>::stream(s, indent + "  ", v.speed_status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "leftw_speed: ";
    Printer<double>::stream(s, indent + "  ", v.leftw_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rightw_speed: ";
    Printer<double>::stream(s, indent + "  ", v.rightw_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gear_model: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_model);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "drive_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.drive_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mow_height: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mow_height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "battery_soc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.battery_soc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_VEHICLEINFO_H
