// Generated by gencpp from file mower_msgs/VehicleStatus.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_VEHICLESTATUS_H
#define MOWER_MSGS_MESSAGE_VEHICLESTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mower_msgs
{
template <class ContainerAllocator>
struct VehicleStatus_
{
  typedef VehicleStatus_<ContainerAllocator> Type;

  VehicleStatus_()
    : header()
    , battery_soc(0)
    , warning_state_one(0)
    , warning_state_two(0)  {
    }
  VehicleStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , battery_soc(0)
    , warning_state_one(0)
    , warning_state_two(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _battery_soc_type;
  _battery_soc_type battery_soc;

   typedef uint8_t _warning_state_one_type;
  _warning_state_one_type warning_state_one;

   typedef uint8_t _warning_state_two_type;
  _warning_state_two_type warning_state_two;





  typedef boost::shared_ptr< ::mower_msgs::VehicleStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::VehicleStatus_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleStatus_

typedef ::mower_msgs::VehicleStatus_<std::allocator<void> > VehicleStatus;

typedef boost::shared_ptr< ::mower_msgs::VehicleStatus > VehicleStatusPtr;
typedef boost::shared_ptr< ::mower_msgs::VehicleStatus const> VehicleStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::VehicleStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::VehicleStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::VehicleStatus_<ContainerAllocator1> & lhs, const ::mower_msgs::VehicleStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.battery_soc == rhs.battery_soc &&
    lhs.warning_state_one == rhs.warning_state_one &&
    lhs.warning_state_two == rhs.warning_state_two;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::VehicleStatus_<ContainerAllocator1> & lhs, const ::mower_msgs::VehicleStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::VehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::VehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::VehicleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::VehicleStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::VehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::VehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::VehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d07e9e512dc3175789403cb7342112b";
  }

  static const char* value(const ::mower_msgs::VehicleStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d07e9e512dc3175ULL;
  static const uint64_t static_value2 = 0x789403cb7342112bULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::VehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/VehicleStatus";
  }

  static const char* value(const ::mower_msgs::VehicleStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::VehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 battery_soc\n"
"uint8 warning_state_one\n"
"uint8 warning_state_two\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mower_msgs::VehicleStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::VehicleStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.battery_soc);
      stream.next(m.warning_state_one);
      stream.next(m.warning_state_two);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::VehicleStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::VehicleStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "battery_soc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.battery_soc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "warning_state_one: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.warning_state_one);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "warning_state_two: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.warning_state_two);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_VEHICLESTATUS_H
