// Generated by gencpp from file mower_msgs/Vslam.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_VSLAM_H
#define MOWER_MSGS_MESSAGE_VSLAM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mower_msgs
{
template <class ContainerAllocator>
struct Vslam_
{
  typedef Vslam_<ContainerAllocator> Type;

  Vslam_()
    : header()
    , local_x(0.0)
    , local_y(0.0)
    , local_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  Vslam_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , local_x(0.0)
    , local_y(0.0)
    , local_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _local_x_type;
  _local_x_type local_x;

   typedef double _local_y_type;
  _local_y_type local_y;

   typedef double _local_z_type;
  _local_z_type local_z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::mower_msgs::Vslam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::Vslam_<ContainerAllocator> const> ConstPtr;

}; // struct Vslam_

typedef ::mower_msgs::Vslam_<std::allocator<void> > Vslam;

typedef boost::shared_ptr< ::mower_msgs::Vslam > VslamPtr;
typedef boost::shared_ptr< ::mower_msgs::Vslam const> VslamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::Vslam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::Vslam_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::Vslam_<ContainerAllocator1> & lhs, const ::mower_msgs::Vslam_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.local_x == rhs.local_x &&
    lhs.local_y == rhs.local_y &&
    lhs.local_z == rhs.local_z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::Vslam_<ContainerAllocator1> & lhs, const ::mower_msgs::Vslam_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Vslam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::Vslam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Vslam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::Vslam_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Vslam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::Vslam_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::Vslam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26eeab7b068d8475f66980c5b18e1bc1";
  }

  static const char* value(const ::mower_msgs::Vslam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26eeab7b068d8475ULL;
  static const uint64_t static_value2 = 0xf66980c5b18e1bc1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::Vslam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/Vslam";
  }

  static const char* value(const ::mower_msgs::Vslam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::Vslam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# VSLAM Position\n"
"Header header\n"
"\n"
"float64 local_x\n"
"float64 local_y\n"
"float64 local_z\n"
"\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mower_msgs::Vslam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::Vslam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.local_x);
      stream.next(m.local_y);
      stream.next(m.local_z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vslam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::Vslam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::Vslam_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_x: ";
    Printer<double>::stream(s, indent + "  ", v.local_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_y: ";
    Printer<double>::stream(s, indent + "  ", v.local_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_z: ";
    Printer<double>::stream(s, indent + "  ", v.local_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_VSLAM_H
