// Generated by gencpp from file mower_msgs/VslamState.msg
// DO NOT EDIT!


#ifndef MOWER_MSGS_MESSAGE_VSLAMSTATE_H
#define MOWER_MSGS_MESSAGE_VSLAMSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mower_msgs
{
template <class ContainerAllocator>
struct VslamState_
{
  typedef VslamState_<ContainerAllocator> Type;

  VslamState_()
    : is_vslam_ok(false)  {
    }
  VslamState_(const ContainerAllocator& _alloc)
    : is_vslam_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_vslam_ok_type;
  _is_vslam_ok_type is_vslam_ok;





  typedef boost::shared_ptr< ::mower_msgs::VslamState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mower_msgs::VslamState_<ContainerAllocator> const> ConstPtr;

}; // struct VslamState_

typedef ::mower_msgs::VslamState_<std::allocator<void> > VslamState;

typedef boost::shared_ptr< ::mower_msgs::VslamState > VslamStatePtr;
typedef boost::shared_ptr< ::mower_msgs::VslamState const> VslamStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mower_msgs::VslamState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mower_msgs::VslamState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mower_msgs::VslamState_<ContainerAllocator1> & lhs, const ::mower_msgs::VslamState_<ContainerAllocator2> & rhs)
{
  return lhs.is_vslam_ok == rhs.is_vslam_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mower_msgs::VslamState_<ContainerAllocator1> & lhs, const ::mower_msgs::VslamState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mower_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::VslamState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mower_msgs::VslamState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::VslamState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mower_msgs::VslamState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::VslamState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mower_msgs::VslamState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mower_msgs::VslamState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d58db3b3d9624dbcc385f025b40a612c";
  }

  static const char* value(const ::mower_msgs::VslamState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd58db3b3d9624dbcULL;
  static const uint64_t static_value2 = 0xc385f025b40a612cULL;
};

template<class ContainerAllocator>
struct DataType< ::mower_msgs::VslamState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mower_msgs/VslamState";
  }

  static const char* value(const ::mower_msgs::VslamState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mower_msgs::VslamState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_vslam_ok\n"
;
  }

  static const char* value(const ::mower_msgs::VslamState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mower_msgs::VslamState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_vslam_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VslamState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mower_msgs::VslamState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mower_msgs::VslamState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "is_vslam_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_vslam_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWER_MSGS_MESSAGE_VSLAMSTATE_H
