// Generated by gencpp from file util/LocalPath.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_LOCALPATH_H
#define UTIL_MESSAGE_LOCALPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct LocalPath_
{
  typedef LocalPath_<ContainerAllocator> Type;

  LocalPath_()
    : header()
    , point_num(0)
    , pathtype(0)
    , x()
    , y()
    , speed()
    , heading()
    , gear()  {
    }
  LocalPath_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point_num(0)
    , pathtype(0)
    , x(_alloc)
    , y(_alloc)
    , speed(_alloc)
    , heading(_alloc)
    , gear(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _point_num_type;
  _point_num_type point_num;

   typedef uint8_t _pathtype_type;
  _pathtype_type pathtype;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_type;
  _x_type x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_type;
  _y_type y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _speed_type;
  _speed_type speed;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _heading_type;
  _heading_type heading;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _gear_type;
  _gear_type gear;





  typedef boost::shared_ptr< ::util::LocalPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::LocalPath_<ContainerAllocator> const> ConstPtr;

}; // struct LocalPath_

typedef ::util::LocalPath_<std::allocator<void> > LocalPath;

typedef boost::shared_ptr< ::util::LocalPath > LocalPathPtr;
typedef boost::shared_ptr< ::util::LocalPath const> LocalPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::LocalPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::LocalPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::LocalPath_<ContainerAllocator1> & lhs, const ::util::LocalPath_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.point_num == rhs.point_num &&
    lhs.pathtype == rhs.pathtype &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.speed == rhs.speed &&
    lhs.heading == rhs.heading &&
    lhs.gear == rhs.gear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::LocalPath_<ContainerAllocator1> & lhs, const ::util::LocalPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::LocalPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::LocalPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::LocalPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::LocalPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::LocalPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::LocalPath_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::LocalPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "badab2507bf5944eff88120326817f6c";
  }

  static const char* value(const ::util::LocalPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbadab2507bf5944eULL;
  static const uint64_t static_value2 = 0xff88120326817f6cULL;
};

template<class ContainerAllocator>
struct DataType< ::util::LocalPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/LocalPath";
  }

  static const char* value(const ::util::LocalPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::LocalPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint8 point_num\n"
"\n"
"uint8 pathtype\n"
"float32[] x\n"
"# m\n"
"\n"
"float32[] y\n"
"# m\n"
"float32[] speed\n"
"# km/h\n"
"\n"
"float32[] heading\n"
"# deg, OX=0, OY=90, 0~360\n"
"\n"
"int8[] gear\n"
"#0-P档，1-d档，2-R档\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::LocalPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::LocalPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point_num);
      stream.next(m.pathtype);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.speed);
      stream.next(m.heading);
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::LocalPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::LocalPath_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.point_num);
    s << indent << "pathtype: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pathtype);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "speed[]" << std::endl;
    for (size_t i = 0; i < v.speed.size(); ++i)
    {
      s << indent << "  speed[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.speed[i]);
    }
    s << indent << "heading[]" << std::endl;
    for (size_t i = 0; i < v.heading.size(); ++i)
    {
      s << indent << "  heading[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.heading[i]);
    }
    s << indent << "gear[]" << std::endl;
    for (size_t i = 0; i < v.gear.size(); ++i)
    {
      s << indent << "  gear[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.gear[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_LOCALPATH_H
