// Generated by gencpp from file util/moving_objects.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_MOVING_OBJECTS_H
#define UTIL_MESSAGE_MOVING_OBJECTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <util/moving_object.h>

namespace util
{
template <class ContainerAllocator>
struct moving_objects_
{
  typedef moving_objects_<ContainerAllocator> Type;

  moving_objects_()
    : header()
    , num(0)
    , moving_obj()  {
    }
  moving_objects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num(0)
    , moving_obj(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _num_type;
  _num_type num;

   typedef std::vector< ::util::moving_object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::util::moving_object_<ContainerAllocator> >> _moving_obj_type;
  _moving_obj_type moving_obj;





  typedef boost::shared_ptr< ::util::moving_objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::moving_objects_<ContainerAllocator> const> ConstPtr;

}; // struct moving_objects_

typedef ::util::moving_objects_<std::allocator<void> > moving_objects;

typedef boost::shared_ptr< ::util::moving_objects > moving_objectsPtr;
typedef boost::shared_ptr< ::util::moving_objects const> moving_objectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::moving_objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::moving_objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::moving_objects_<ContainerAllocator1> & lhs, const ::util::moving_objects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.num == rhs.num &&
    lhs.moving_obj == rhs.moving_obj;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::moving_objects_<ContainerAllocator1> & lhs, const ::util::moving_objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::moving_objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::moving_objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::moving_objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::moving_objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::moving_objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::moving_objects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::moving_objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c433c9a0e5b7d198518fcd1e6805968";
  }

  static const char* value(const ::util::moving_objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c433c9a0e5b7d19ULL;
  static const uint64_t static_value2 = 0x8518fcd1e6805968ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::moving_objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/moving_objects";
  }

  static const char* value(const ::util::moving_objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::moving_objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 num\n"
"moving_object[] moving_obj\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: util/moving_object\n"
"#relative position, m\n"
"float32 x1 # x_min\n"
"float32 y1 # y_min\n"
"float32 x2 # x_min\n"
"float32 y2 # y_max\n"
"float32 x3 # x_max\n"
"float32 y3 # y_max\n"
"float32 x4 # x_max\n"
"float32 y4 # y_min\n"
"\n"
"# height, cm\n"
"float32 zmin\n"
"\n"
"float32 zmax\n"
"\n"
"# absolute speed, m/s\n"
"float32 speed\n"
"\n"
"# deg\n"
"float32 speed_direction\n"
"\n"
"uint32 id\n"
"string label\n"
"\n"
"# center point coordinate in localpose frame, m\n"
"float32 global_x\n"
"float32 global_y\n"
"\n"
"float32 local_x\n"
"float32 local_y\n"
;
  }

  static const char* value(const ::util::moving_objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::moving_objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num);
      stream.next(m.moving_obj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moving_objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::moving_objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::moving_objects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    s << indent << "moving_obj[]" << std::endl;
    for (size_t i = 0; i < v.moving_obj.size(); ++i)
    {
      s << indent << "  moving_obj[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::util::moving_object_<ContainerAllocator> >::stream(s, indent + "    ", v.moving_obj[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_MOVING_OBJECTS_H
