// Generated by gencpp from file util/moving_object.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_MOVING_OBJECT_H
#define UTIL_MESSAGE_MOVING_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace util
{
template <class ContainerAllocator>
struct moving_object_
{
  typedef moving_object_<ContainerAllocator> Type;

  moving_object_()
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , x3(0.0)
    , y3(0.0)
    , x4(0.0)
    , y4(0.0)
    , zmin(0.0)
    , zmax(0.0)
    , speed(0.0)
    , speed_direction(0.0)
    , id(0)
    , label()
    , global_x(0.0)
    , global_y(0.0)
    , local_x(0.0)
    , local_y(0.0)  {
    }
  moving_object_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , x3(0.0)
    , y3(0.0)
    , x4(0.0)
    , y4(0.0)
    , zmin(0.0)
    , zmax(0.0)
    , speed(0.0)
    , speed_direction(0.0)
    , id(0)
    , label(_alloc)
    , global_x(0.0)
    , global_y(0.0)
    , local_x(0.0)
    , local_y(0.0)  {
  (void)_alloc;
    }



   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _x2_type;
  _x2_type x2;

   typedef float _y2_type;
  _y2_type y2;

   typedef float _x3_type;
  _x3_type x3;

   typedef float _y3_type;
  _y3_type y3;

   typedef float _x4_type;
  _x4_type x4;

   typedef float _y4_type;
  _y4_type y4;

   typedef float _zmin_type;
  _zmin_type zmin;

   typedef float _zmax_type;
  _zmax_type zmax;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _speed_direction_type;
  _speed_direction_type speed_direction;

   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef float _global_x_type;
  _global_x_type global_x;

   typedef float _global_y_type;
  _global_y_type global_y;

   typedef float _local_x_type;
  _local_x_type local_x;

   typedef float _local_y_type;
  _local_y_type local_y;





  typedef boost::shared_ptr< ::util::moving_object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::moving_object_<ContainerAllocator> const> ConstPtr;

}; // struct moving_object_

typedef ::util::moving_object_<std::allocator<void> > moving_object;

typedef boost::shared_ptr< ::util::moving_object > moving_objectPtr;
typedef boost::shared_ptr< ::util::moving_object const> moving_objectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::moving_object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::moving_object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::moving_object_<ContainerAllocator1> & lhs, const ::util::moving_object_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2 &&
    lhs.x3 == rhs.x3 &&
    lhs.y3 == rhs.y3 &&
    lhs.x4 == rhs.x4 &&
    lhs.y4 == rhs.y4 &&
    lhs.zmin == rhs.zmin &&
    lhs.zmax == rhs.zmax &&
    lhs.speed == rhs.speed &&
    lhs.speed_direction == rhs.speed_direction &&
    lhs.id == rhs.id &&
    lhs.label == rhs.label &&
    lhs.global_x == rhs.global_x &&
    lhs.global_y == rhs.global_y &&
    lhs.local_x == rhs.local_x &&
    lhs.local_y == rhs.local_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::moving_object_<ContainerAllocator1> & lhs, const ::util::moving_object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::moving_object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::moving_object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::moving_object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::moving_object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::moving_object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::moving_object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::moving_object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7cd6ca358df051582ae0af990bcae84b";
  }

  static const char* value(const ::util::moving_object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7cd6ca358df05158ULL;
  static const uint64_t static_value2 = 0x2ae0af990bcae84bULL;
};

template<class ContainerAllocator>
struct DataType< ::util::moving_object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/moving_object";
  }

  static const char* value(const ::util::moving_object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::moving_object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#relative position, m\n"
"float32 x1 # x_min\n"
"float32 y1 # y_min\n"
"float32 x2 # x_min\n"
"float32 y2 # y_max\n"
"float32 x3 # x_max\n"
"float32 y3 # y_max\n"
"float32 x4 # x_max\n"
"float32 y4 # y_min\n"
"\n"
"# height, cm\n"
"float32 zmin\n"
"\n"
"float32 zmax\n"
"\n"
"# absolute speed, m/s\n"
"float32 speed\n"
"\n"
"# deg\n"
"float32 speed_direction\n"
"\n"
"uint32 id\n"
"string label\n"
"\n"
"# center point coordinate in localpose frame, m\n"
"float32 global_x\n"
"float32 global_y\n"
"\n"
"float32 local_x\n"
"float32 local_y\n"
;
  }

  static const char* value(const ::util::moving_object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::moving_object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.x3);
      stream.next(m.y3);
      stream.next(m.x4);
      stream.next(m.y4);
      stream.next(m.zmin);
      stream.next(m.zmax);
      stream.next(m.speed);
      stream.next(m.speed_direction);
      stream.next(m.id);
      stream.next(m.label);
      stream.next(m.global_x);
      stream.next(m.global_y);
      stream.next(m.local_x);
      stream.next(m.local_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moving_object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::moving_object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::moving_object_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<float>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<float>::stream(s, indent + "  ", v.y2);
    s << indent << "x3: ";
    Printer<float>::stream(s, indent + "  ", v.x3);
    s << indent << "y3: ";
    Printer<float>::stream(s, indent + "  ", v.y3);
    s << indent << "x4: ";
    Printer<float>::stream(s, indent + "  ", v.x4);
    s << indent << "y4: ";
    Printer<float>::stream(s, indent + "  ", v.y4);
    s << indent << "zmin: ";
    Printer<float>::stream(s, indent + "  ", v.zmin);
    s << indent << "zmax: ";
    Printer<float>::stream(s, indent + "  ", v.zmax);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "speed_direction: ";
    Printer<float>::stream(s, indent + "  ", v.speed_direction);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    s << indent << "global_x: ";
    Printer<float>::stream(s, indent + "  ", v.global_x);
    s << indent << "global_y: ";
    Printer<float>::stream(s, indent + "  ", v.global_y);
    s << indent << "local_x: ";
    Printer<float>::stream(s, indent + "  ", v.local_x);
    s << indent << "local_y: ";
    Printer<float>::stream(s, indent + "  ", v.local_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_MOVING_OBJECT_H
