// Generated by gencpp from file util/Obstacle.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_OBSTACLE_H
#define UTIL_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : header()
    , local_x(0.0)
    , local_y(0.0)
    , global_x(0.0)
    , global_y(0.0)
    , x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , x3(0.0)
    , y3(0.0)
    , x4(0.0)
    , y4(0.0)
    , is_dynamic(false)  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , local_x(0.0)
    , local_y(0.0)
    , global_x(0.0)
    , global_y(0.0)
    , x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , x3(0.0)
    , y3(0.0)
    , x4(0.0)
    , y4(0.0)
    , is_dynamic(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _local_x_type;
  _local_x_type local_x;

   typedef double _local_y_type;
  _local_y_type local_y;

   typedef double _global_x_type;
  _global_x_type global_x;

   typedef double _global_y_type;
  _global_y_type global_y;

   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _x2_type;
  _x2_type x2;

   typedef float _y2_type;
  _y2_type y2;

   typedef float _x3_type;
  _x3_type x3;

   typedef float _y3_type;
  _y3_type y3;

   typedef float _x4_type;
  _x4_type x4;

   typedef float _y4_type;
  _y4_type y4;

   typedef uint8_t _is_dynamic_type;
  _is_dynamic_type is_dynamic;





  typedef boost::shared_ptr< ::util::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::util::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::util::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::util::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::Obstacle_<ContainerAllocator1> & lhs, const ::util::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.local_x == rhs.local_x &&
    lhs.local_y == rhs.local_y &&
    lhs.global_x == rhs.global_x &&
    lhs.global_y == rhs.global_y &&
    lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2 &&
    lhs.x3 == rhs.x3 &&
    lhs.y3 == rhs.y3 &&
    lhs.x4 == rhs.x4 &&
    lhs.y4 == rhs.y4 &&
    lhs.is_dynamic == rhs.is_dynamic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::Obstacle_<ContainerAllocator1> & lhs, const ::util::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9cfcfb9d59a900ca50b3ef55c2eb450b";
  }

  static const char* value(const ::util::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9cfcfb9d59a900caULL;
  static const uint64_t static_value2 = 0x50b3ef55c2eb450bULL;
};

template<class ContainerAllocator>
struct DataType< ::util::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/Obstacle";
  }

  static const char* value(const ::util::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# 2D Box\n"
"float64 local_x # m, in map\n"
"float64 local_y # m, in map\n"
"float64 global_x\n"
"float64 global_y\n"
"float32 x1 # x_min\n"
"float32 y1 # y_max\n"
"float32 x2 # x_max\n"
"float32 y2 # y_max\n"
"float32 x3 # x_max\n"
"float32 y3 # y_min\n"
"float32 x4 # x_min\n"
"float32 y4 # y_min\n"
"bool is_dynamic # is_dynamic\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.local_x);
      stream.next(m.local_y);
      stream.next(m.global_x);
      stream.next(m.global_y);
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.x3);
      stream.next(m.y3);
      stream.next(m.x4);
      stream.next(m.y4);
      stream.next(m.is_dynamic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "local_x: ";
    Printer<double>::stream(s, indent + "  ", v.local_x);
    s << indent << "local_y: ";
    Printer<double>::stream(s, indent + "  ", v.local_y);
    s << indent << "global_x: ";
    Printer<double>::stream(s, indent + "  ", v.global_x);
    s << indent << "global_y: ";
    Printer<double>::stream(s, indent + "  ", v.global_y);
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<float>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<float>::stream(s, indent + "  ", v.y2);
    s << indent << "x3: ";
    Printer<float>::stream(s, indent + "  ", v.x3);
    s << indent << "y3: ";
    Printer<float>::stream(s, indent + "  ", v.y3);
    s << indent << "x4: ";
    Printer<float>::stream(s, indent + "  ", v.x4);
    s << indent << "y4: ";
    Printer<float>::stream(s, indent + "  ", v.y4);
    s << indent << "is_dynamic: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_dynamic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_OBSTACLE_H
