// Generated by gencpp from file util/ObstacleList.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_OBSTACLELIST_H
#define UTIL_MESSAGE_OBSTACLELIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <util/Obstacle.h>

namespace util
{
template <class ContainerAllocator>
struct ObstacleList_
{
  typedef ObstacleList_<ContainerAllocator> Type;

  ObstacleList_()
    : header()
    , obstacles()  {
    }
  ObstacleList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::util::Obstacle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::util::Obstacle_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::util::ObstacleList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::ObstacleList_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleList_

typedef ::util::ObstacleList_<std::allocator<void> > ObstacleList;

typedef boost::shared_ptr< ::util::ObstacleList > ObstacleListPtr;
typedef boost::shared_ptr< ::util::ObstacleList const> ObstacleListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::ObstacleList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::ObstacleList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::ObstacleList_<ContainerAllocator1> & lhs, const ::util::ObstacleList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::ObstacleList_<ContainerAllocator1> & lhs, const ::util::ObstacleList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::ObstacleList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::ObstacleList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::ObstacleList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::ObstacleList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::ObstacleList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::ObstacleList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed84bcdb508e0ed6125f51a05240a67b";
  }

  static const char* value(const ::util::ObstacleList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed84bcdb508e0ed6ULL;
  static const uint64_t static_value2 = 0x125f51a05240a67bULL;
};

template<class ContainerAllocator>
struct DataType< ::util::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/ObstacleList";
  }

  static const char* value(const ::util::ObstacleList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Obstacle[] obstacles\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: util/Obstacle\n"
"Header header\n"
"\n"
"# 2D Box\n"
"float64 local_x # m, in map\n"
"float64 local_y # m, in map\n"
"float64 global_x\n"
"float64 global_y\n"
"float32 x1 # x_min\n"
"float32 y1 # y_max\n"
"float32 x2 # x_max\n"
"float32 y2 # y_max\n"
"float32 x3 # x_max\n"
"float32 y3 # y_min\n"
"float32 x4 # x_min\n"
"float32 y4 # y_min\n"
"bool is_dynamic # is_dynamic\n"
;
  }

  static const char* value(const ::util::ObstacleList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::ObstacleList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::ObstacleList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::ObstacleList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::util::Obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_OBSTACLELIST_H
