// Generated by gencpp from file util/Position.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_POSITION_H
#define UTIL_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : header()
    , position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , position_state(0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , position_state(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _position_x_type;
  _position_x_type position_x;

   typedef double _position_y_type;
  _position_y_type position_y;

   typedef double _position_z_type;
  _position_z_type position_z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef uint32_t _position_state_type;
  _position_state_type position_state;





  typedef boost::shared_ptr< ::util::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::util::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::util::Position > PositionPtr;
typedef boost::shared_ptr< ::util::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::Position_<ContainerAllocator1> & lhs, const ::util::Position_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_z == rhs.position_z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.position_state == rhs.position_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::Position_<ContainerAllocator1> & lhs, const ::util::Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::Position_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::Position_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b162b5fae3a9f45d1742394d3c0bb3a6";
  }

  static const char* value(const ::util::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb162b5fae3a9f45dULL;
  static const uint64_t static_value2 = 0x1742394d3c0bb3a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/Position";
  }

  static const char* value(const ::util::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 position_x\n"
"float64 position_y\n"
"float64 position_z\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"uint32  position_state\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.position_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::Position_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position_x: ";
    Printer<double>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<double>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_z: ";
    Printer<double>::stream(s, indent + "  ", v.position_z);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "position_state: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.position_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_POSITION_H
