// Generated by gencpp from file util/VehicleInfoTest.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_VEHICLEINFOTEST_H
#define UTIL_MESSAGE_VEHICLEINFOTEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct VehicleInfoTest_
{
  typedef VehicleInfoTest_<ContainerAllocator> Type;

  VehicleInfoTest_()
    : header()
    , speed_status(0.0)
    , angle_status(0.0)  {
    }
  VehicleInfoTest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed_status(0.0)
    , angle_status(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _speed_status_type;
  _speed_status_type speed_status;

   typedef double _angle_status_type;
  _angle_status_type angle_status;





  typedef boost::shared_ptr< ::util::VehicleInfoTest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::VehicleInfoTest_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleInfoTest_

typedef ::util::VehicleInfoTest_<std::allocator<void> > VehicleInfoTest;

typedef boost::shared_ptr< ::util::VehicleInfoTest > VehicleInfoTestPtr;
typedef boost::shared_ptr< ::util::VehicleInfoTest const> VehicleInfoTestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::VehicleInfoTest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::VehicleInfoTest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::VehicleInfoTest_<ContainerAllocator1> & lhs, const ::util::VehicleInfoTest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.speed_status == rhs.speed_status &&
    lhs.angle_status == rhs.angle_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::VehicleInfoTest_<ContainerAllocator1> & lhs, const ::util::VehicleInfoTest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::VehicleInfoTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::VehicleInfoTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::VehicleInfoTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::VehicleInfoTest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::VehicleInfoTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::VehicleInfoTest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::VehicleInfoTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c82651e7ec09ce256b0ec03b6f2bab7";
  }

  static const char* value(const ::util::VehicleInfoTest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c82651e7ec09ce2ULL;
  static const uint64_t static_value2 = 0x56b0ec03b6f2bab7ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::VehicleInfoTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/VehicleInfoTest";
  }

  static const char* value(const ::util::VehicleInfoTest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::VehicleInfoTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# AGVStatus 0x201\n"
"float64 speed_status\n"
"float64 angle_status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::VehicleInfoTest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::VehicleInfoTest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed_status);
      stream.next(m.angle_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleInfoTest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::VehicleInfoTest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::VehicleInfoTest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed_status: ";
    Printer<double>::stream(s, indent + "  ", v.speed_status);
    s << indent << "angle_status: ";
    Printer<double>::stream(s, indent + "  ", v.angle_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_VEHICLEINFOTEST_H
