// Generated by gencpp from file util/VehicleControl.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_VEHICLECONTROL_H
#define UTIL_MESSAGE_VEHICLECONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct VehicleControl_
{
  typedef VehicleControl_<ContainerAllocator> Type;

  VehicleControl_()
    : header()
    , mover_bool(0)
    , ad_control_enable(0)
    , gear_model(0)
    , turn_value(0)
    , drive_value(0)
    , mower_height(0)
    , left_wheel_speed(0.0)
    , right_wheel_speed(0.0)
    , speed_cmd(0.0)  {
    }
  VehicleControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mover_bool(0)
    , ad_control_enable(0)
    , gear_model(0)
    , turn_value(0)
    , drive_value(0)
    , mower_height(0)
    , left_wheel_speed(0.0)
    , right_wheel_speed(0.0)
    , speed_cmd(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mover_bool_type;
  _mover_bool_type mover_bool;

   typedef uint8_t _ad_control_enable_type;
  _ad_control_enable_type ad_control_enable;

   typedef uint8_t _gear_model_type;
  _gear_model_type gear_model;

   typedef uint16_t _turn_value_type;
  _turn_value_type turn_value;

   typedef uint16_t _drive_value_type;
  _drive_value_type drive_value;

   typedef uint8_t _mower_height_type;
  _mower_height_type mower_height;

   typedef double _left_wheel_speed_type;
  _left_wheel_speed_type left_wheel_speed;

   typedef double _right_wheel_speed_type;
  _right_wheel_speed_type right_wheel_speed;

   typedef double _speed_cmd_type;
  _speed_cmd_type speed_cmd;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(p_Gear)
  #undef p_Gear
#endif
#if defined(_WIN32) && defined(R_Gear)
  #undef R_Gear
#endif
#if defined(_WIN32) && defined(N_Gear)
  #undef N_Gear
#endif
#if defined(_WIN32) && defined(D_Gear)
  #undef D_Gear
#endif

  enum {
    p_Gear = 0u,
    R_Gear = 1u,
    N_Gear = 2u,
    D_Gear = 3u,
  };


  typedef boost::shared_ptr< ::util::VehicleControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::VehicleControl_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleControl_

typedef ::util::VehicleControl_<std::allocator<void> > VehicleControl;

typedef boost::shared_ptr< ::util::VehicleControl > VehicleControlPtr;
typedef boost::shared_ptr< ::util::VehicleControl const> VehicleControlConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::VehicleControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::VehicleControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::VehicleControl_<ContainerAllocator1> & lhs, const ::util::VehicleControl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mover_bool == rhs.mover_bool &&
    lhs.ad_control_enable == rhs.ad_control_enable &&
    lhs.gear_model == rhs.gear_model &&
    lhs.turn_value == rhs.turn_value &&
    lhs.drive_value == rhs.drive_value &&
    lhs.mower_height == rhs.mower_height &&
    lhs.left_wheel_speed == rhs.left_wheel_speed &&
    lhs.right_wheel_speed == rhs.right_wheel_speed &&
    lhs.speed_cmd == rhs.speed_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::VehicleControl_<ContainerAllocator1> & lhs, const ::util::VehicleControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::VehicleControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::VehicleControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::VehicleControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::VehicleControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::VehicleControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::VehicleControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::VehicleControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4cc34e4fcf9d1ca27ccdd1d58a91a49";
  }

  static const char* value(const ::util::VehicleControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4cc34e4fcf9d1caULL;
  static const uint64_t static_value2 = 0x27ccdd1d58a91a49ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::VehicleControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/VehicleControl";
  }

  static const char* value(const ::util::VehicleControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::VehicleControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"# VehicleCmd\n"
"# Gear_model\n"
"uint8 p_Gear = 0 # 0x00： P 档\n"
"uint8 R_Gear = 1 # 0x01： 无\n"
"uint8 N_Gear = 2 # 0x02： 转弯信号\n"
"uint8 D_Gear = 3 # 0x03： D 前进档\n"
"\n"
"# ADCmd 0x310\n"
"uint8 mover_bool\n"
"uint8 ad_control_enable \n"
"uint8 gear_model\n"
"uint16 turn_value\n"
"uint16 drive_value\n"
"uint8 mower_height\n"
"\n"
"float64 left_wheel_speed  # 无\n"
"float64 right_wheel_speed # 无\n"
"float64 speed_cmd   # int8 [-128~127]\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::VehicleControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::VehicleControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mover_bool);
      stream.next(m.ad_control_enable);
      stream.next(m.gear_model);
      stream.next(m.turn_value);
      stream.next(m.drive_value);
      stream.next(m.mower_height);
      stream.next(m.left_wheel_speed);
      stream.next(m.right_wheel_speed);
      stream.next(m.speed_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::VehicleControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::VehicleControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mover_bool: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mover_bool);
    s << indent << "ad_control_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ad_control_enable);
    s << indent << "gear_model: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_model);
    s << indent << "turn_value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.turn_value);
    s << indent << "drive_value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.drive_value);
    s << indent << "mower_height: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mower_height);
    s << indent << "left_wheel_speed: ";
    Printer<double>::stream(s, indent + "  ", v.left_wheel_speed);
    s << indent << "right_wheel_speed: ";
    Printer<double>::stream(s, indent + "  ", v.right_wheel_speed);
    s << indent << "speed_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.speed_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_VEHICLECONTROL_H
