// Generated by gencpp from file util/err.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_ERR_H
#define UTIL_MESSAGE_ERR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct err_
{
  typedef err_<ContainerAllocator> Type;

  err_()
    : header()
    , ant_e(0.0)
    , ant_n(0.0)
    , ant_u(0.0)
    , ant_yaw(0.0)
    , dual_yaw(0.0)
    , dual_e(0.0)
    , dual_n(0.0)
    , dual_u(0.0)
    , slam_x(0.0)
    , slam_y(0.0)
    , err_e(0.0)
    , err_n(0.0)
    , err_u(0.0)
    , err_yaw(0.0)
    , err_slame(0.0)
    , err_slamn(0.0)
    , err_slamu(0.0)
    , err_slamyaw(0.0)  {
    }
  err_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ant_e(0.0)
    , ant_n(0.0)
    , ant_u(0.0)
    , ant_yaw(0.0)
    , dual_yaw(0.0)
    , dual_e(0.0)
    , dual_n(0.0)
    , dual_u(0.0)
    , slam_x(0.0)
    , slam_y(0.0)
    , err_e(0.0)
    , err_n(0.0)
    , err_u(0.0)
    , err_yaw(0.0)
    , err_slame(0.0)
    , err_slamn(0.0)
    , err_slamu(0.0)
    , err_slamyaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _ant_e_type;
  _ant_e_type ant_e;

   typedef double _ant_n_type;
  _ant_n_type ant_n;

   typedef double _ant_u_type;
  _ant_u_type ant_u;

   typedef double _ant_yaw_type;
  _ant_yaw_type ant_yaw;

   typedef double _dual_yaw_type;
  _dual_yaw_type dual_yaw;

   typedef double _dual_e_type;
  _dual_e_type dual_e;

   typedef double _dual_n_type;
  _dual_n_type dual_n;

   typedef double _dual_u_type;
  _dual_u_type dual_u;

   typedef double _slam_x_type;
  _slam_x_type slam_x;

   typedef double _slam_y_type;
  _slam_y_type slam_y;

   typedef double _err_e_type;
  _err_e_type err_e;

   typedef double _err_n_type;
  _err_n_type err_n;

   typedef double _err_u_type;
  _err_u_type err_u;

   typedef double _err_yaw_type;
  _err_yaw_type err_yaw;

   typedef double _err_slame_type;
  _err_slame_type err_slame;

   typedef double _err_slamn_type;
  _err_slamn_type err_slamn;

   typedef double _err_slamu_type;
  _err_slamu_type err_slamu;

   typedef double _err_slamyaw_type;
  _err_slamyaw_type err_slamyaw;





  typedef boost::shared_ptr< ::util::err_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::err_<ContainerAllocator> const> ConstPtr;

}; // struct err_

typedef ::util::err_<std::allocator<void> > err;

typedef boost::shared_ptr< ::util::err > errPtr;
typedef boost::shared_ptr< ::util::err const> errConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::err_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::err_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::err_<ContainerAllocator1> & lhs, const ::util::err_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ant_e == rhs.ant_e &&
    lhs.ant_n == rhs.ant_n &&
    lhs.ant_u == rhs.ant_u &&
    lhs.ant_yaw == rhs.ant_yaw &&
    lhs.dual_yaw == rhs.dual_yaw &&
    lhs.dual_e == rhs.dual_e &&
    lhs.dual_n == rhs.dual_n &&
    lhs.dual_u == rhs.dual_u &&
    lhs.slam_x == rhs.slam_x &&
    lhs.slam_y == rhs.slam_y &&
    lhs.err_e == rhs.err_e &&
    lhs.err_n == rhs.err_n &&
    lhs.err_u == rhs.err_u &&
    lhs.err_yaw == rhs.err_yaw &&
    lhs.err_slame == rhs.err_slame &&
    lhs.err_slamn == rhs.err_slamn &&
    lhs.err_slamu == rhs.err_slamu &&
    lhs.err_slamyaw == rhs.err_slamyaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::err_<ContainerAllocator1> & lhs, const ::util::err_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::err_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::err_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::err_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::err_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::err_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::err_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::err_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e17d8731f8e0158fd085ddb259f3fb3";
  }

  static const char* value(const ::util::err_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e17d8731f8e0158ULL;
  static const uint64_t static_value2 = 0xfd085ddb259f3fb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::err_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/err";
  }

  static const char* value(const ::util::err_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::err_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 ant_e\n"
"float64 ant_n\n"
"float64 ant_u\n"
"float64 ant_yaw\n"
"float64 dual_yaw\n"
"float64 dual_e\n"
"float64 dual_n\n"
"float64 dual_u\n"
"float64 slam_x\n"
"float64 slam_y\n"
"float64 err_e \n"
"float64 err_n\n"
"float64 err_u\n"
"float64 err_yaw\n"
"float64 err_slame\n"
"float64 err_slamn\n"
"float64 err_slamu\n"
"float64 err_slamyaw \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::err_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::err_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ant_e);
      stream.next(m.ant_n);
      stream.next(m.ant_u);
      stream.next(m.ant_yaw);
      stream.next(m.dual_yaw);
      stream.next(m.dual_e);
      stream.next(m.dual_n);
      stream.next(m.dual_u);
      stream.next(m.slam_x);
      stream.next(m.slam_y);
      stream.next(m.err_e);
      stream.next(m.err_n);
      stream.next(m.err_u);
      stream.next(m.err_yaw);
      stream.next(m.err_slame);
      stream.next(m.err_slamn);
      stream.next(m.err_slamu);
      stream.next(m.err_slamyaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct err_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::err_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::err_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ant_e: ";
    Printer<double>::stream(s, indent + "  ", v.ant_e);
    s << indent << "ant_n: ";
    Printer<double>::stream(s, indent + "  ", v.ant_n);
    s << indent << "ant_u: ";
    Printer<double>::stream(s, indent + "  ", v.ant_u);
    s << indent << "ant_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.ant_yaw);
    s << indent << "dual_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.dual_yaw);
    s << indent << "dual_e: ";
    Printer<double>::stream(s, indent + "  ", v.dual_e);
    s << indent << "dual_n: ";
    Printer<double>::stream(s, indent + "  ", v.dual_n);
    s << indent << "dual_u: ";
    Printer<double>::stream(s, indent + "  ", v.dual_u);
    s << indent << "slam_x: ";
    Printer<double>::stream(s, indent + "  ", v.slam_x);
    s << indent << "slam_y: ";
    Printer<double>::stream(s, indent + "  ", v.slam_y);
    s << indent << "err_e: ";
    Printer<double>::stream(s, indent + "  ", v.err_e);
    s << indent << "err_n: ";
    Printer<double>::stream(s, indent + "  ", v.err_n);
    s << indent << "err_u: ";
    Printer<double>::stream(s, indent + "  ", v.err_u);
    s << indent << "err_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.err_yaw);
    s << indent << "err_slame: ";
    Printer<double>::stream(s, indent + "  ", v.err_slame);
    s << indent << "err_slamn: ";
    Printer<double>::stream(s, indent + "  ", v.err_slamn);
    s << indent << "err_slamu: ";
    Printer<double>::stream(s, indent + "  ", v.err_slamu);
    s << indent << "err_slamyaw: ";
    Printer<double>::stream(s, indent + "  ", v.err_slamyaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_ERR_H
