// Generated by gencpp from file util/ImuStaticCalibration.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_IMUSTATICCALIBRATION_H
#define UTIL_MESSAGE_IMUSTATICCALIBRATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct ImuStaticCalibration_
{
  typedef ImuStaticCalibration_<ContainerAllocator> Type;

  ImuStaticCalibration_()
    : header()
    , valid(false)
    , lio_generation()
    , imu_topic()
    , duration_sec(0.0)
    , sample_count(0)
    , mean_acceleration_mps2()
    , mean_angular_velocity_radps()
    , acceleration_variance()
    , angular_velocity_variance()
    , max_angular_velocity_norm_radps(0.0)  {
      mean_acceleration_mps2.assign(0.0);

      mean_angular_velocity_radps.assign(0.0);

      acceleration_variance.assign(0.0);

      angular_velocity_variance.assign(0.0);
  }
  ImuStaticCalibration_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , valid(false)
    , lio_generation()
    , imu_topic(_alloc)
    , duration_sec(0.0)
    , sample_count(0)
    , mean_acceleration_mps2()
    , mean_angular_velocity_radps()
    , acceleration_variance()
    , angular_velocity_variance()
    , max_angular_velocity_norm_radps(0.0)  {
  (void)_alloc;
      mean_acceleration_mps2.assign(0.0);

      mean_angular_velocity_radps.assign(0.0);

      acceleration_variance.assign(0.0);

      angular_velocity_variance.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef ros::Time _lio_generation_type;
  _lio_generation_type lio_generation;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _imu_topic_type;
  _imu_topic_type imu_topic;

   typedef double _duration_sec_type;
  _duration_sec_type duration_sec;

   typedef uint32_t _sample_count_type;
  _sample_count_type sample_count;

   typedef boost::array<double, 3>  _mean_acceleration_mps2_type;
  _mean_acceleration_mps2_type mean_acceleration_mps2;

   typedef boost::array<double, 3>  _mean_angular_velocity_radps_type;
  _mean_angular_velocity_radps_type mean_angular_velocity_radps;

   typedef boost::array<double, 3>  _acceleration_variance_type;
  _acceleration_variance_type acceleration_variance;

   typedef boost::array<double, 3>  _angular_velocity_variance_type;
  _angular_velocity_variance_type angular_velocity_variance;

   typedef double _max_angular_velocity_norm_radps_type;
  _max_angular_velocity_norm_radps_type max_angular_velocity_norm_radps;





  typedef boost::shared_ptr< ::util::ImuStaticCalibration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::ImuStaticCalibration_<ContainerAllocator> const> ConstPtr;

}; // struct ImuStaticCalibration_

typedef ::util::ImuStaticCalibration_<std::allocator<void> > ImuStaticCalibration;

typedef boost::shared_ptr< ::util::ImuStaticCalibration > ImuStaticCalibrationPtr;
typedef boost::shared_ptr< ::util::ImuStaticCalibration const> ImuStaticCalibrationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::ImuStaticCalibration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::ImuStaticCalibration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::ImuStaticCalibration_<ContainerAllocator1> & lhs, const ::util::ImuStaticCalibration_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.valid == rhs.valid &&
    lhs.lio_generation == rhs.lio_generation &&
    lhs.imu_topic == rhs.imu_topic &&
    lhs.duration_sec == rhs.duration_sec &&
    lhs.sample_count == rhs.sample_count &&
    lhs.mean_acceleration_mps2 == rhs.mean_acceleration_mps2 &&
    lhs.mean_angular_velocity_radps == rhs.mean_angular_velocity_radps &&
    lhs.acceleration_variance == rhs.acceleration_variance &&
    lhs.angular_velocity_variance == rhs.angular_velocity_variance &&
    lhs.max_angular_velocity_norm_radps == rhs.max_angular_velocity_norm_radps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::ImuStaticCalibration_<ContainerAllocator1> & lhs, const ::util::ImuStaticCalibration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::ImuStaticCalibration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::ImuStaticCalibration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::ImuStaticCalibration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::ImuStaticCalibration_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::ImuStaticCalibration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::ImuStaticCalibration_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::ImuStaticCalibration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18a255ee627c55f5a95de2c4231b1512";
  }

  static const char* value(const ::util::ImuStaticCalibration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18a255ee627c55f5ULL;
  static const uint64_t static_value2 = 0xa95de2c4231b1512ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::ImuStaticCalibration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/ImuStaticCalibration";
  }

  static const char* value(const ::util::ImuStaticCalibration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::ImuStaticCalibration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# FAST-LIO权威静止初始化窗口统计。消息由/laserMapping锁存发布；\n"
"# header.stamp是该静止窗口最后一帧IMU的传感器时间，header.frame_id是原始IMU坐标系。\n"
"Header header\n"
"bool valid\n"
"time lio_generation\n"
"string imu_topic\n"
"float64 duration_sec\n"
"uint32 sample_count\n"
"float64[3] mean_acceleration_mps2\n"
"float64[3] mean_angular_velocity_radps\n"
"float64[3] acceleration_variance\n"
"float64[3] angular_velocity_variance\n"
"float64 max_angular_velocity_norm_radps\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::ImuStaticCalibration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::ImuStaticCalibration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.valid);
      stream.next(m.lio_generation);
      stream.next(m.imu_topic);
      stream.next(m.duration_sec);
      stream.next(m.sample_count);
      stream.next(m.mean_acceleration_mps2);
      stream.next(m.mean_angular_velocity_radps);
      stream.next(m.acceleration_variance);
      stream.next(m.angular_velocity_variance);
      stream.next(m.max_angular_velocity_norm_radps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuStaticCalibration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::ImuStaticCalibration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::ImuStaticCalibration_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "lio_generation: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.lio_generation);
    s << indent << "imu_topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.imu_topic);
    s << indent << "duration_sec: ";
    Printer<double>::stream(s, indent + "  ", v.duration_sec);
    s << indent << "sample_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sample_count);
    s << indent << "mean_acceleration_mps2[]" << std::endl;
    for (size_t i = 0; i < v.mean_acceleration_mps2.size(); ++i)
    {
      s << indent << "  mean_acceleration_mps2[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.mean_acceleration_mps2[i]);
    }
    s << indent << "mean_angular_velocity_radps[]" << std::endl;
    for (size_t i = 0; i < v.mean_angular_velocity_radps.size(); ++i)
    {
      s << indent << "  mean_angular_velocity_radps[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.mean_angular_velocity_radps[i]);
    }
    s << indent << "acceleration_variance[]" << std::endl;
    for (size_t i = 0; i < v.acceleration_variance.size(); ++i)
    {
      s << indent << "  acceleration_variance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.acceleration_variance[i]);
    }
    s << indent << "angular_velocity_variance[]" << std::endl;
    for (size_t i = 0; i < v.angular_velocity_variance.size(); ++i)
    {
      s << indent << "  angular_velocity_variance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angular_velocity_variance[i]);
    }
    s << indent << "max_angular_velocity_norm_radps: ";
    Printer<double>::stream(s, indent + "  ", v.max_angular_velocity_norm_radps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_IMUSTATICCALIBRATION_H
