// Generated by gencpp from file util/ManageLocalizationMapResponse.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_MANAGELOCALIZATIONMAPRESPONSE_H
#define UTIL_MESSAGE_MANAGELOCALIZATIONMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace util
{
template <class ContainerAllocator>
struct ManageLocalizationMapResponse_
{
  typedef ManageLocalizationMapResponse_<ContainerAllocator> Type;

  ManageLocalizationMapResponse_()
    : success(false)
    , alignment_preserved(false)
    , switch_pending(false)
    , active_map()
    , active_map_uuid()
    , pending_map()
    , pending_map_uuid()
    , map_schema_version(0)
    , coordinate_frame()
    , origin_checksum()
    , reason()  {
    }
  ManageLocalizationMapResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , alignment_preserved(false)
    , switch_pending(false)
    , active_map(_alloc)
    , active_map_uuid(_alloc)
    , pending_map(_alloc)
    , pending_map_uuid(_alloc)
    , map_schema_version(0)
    , coordinate_frame(_alloc)
    , origin_checksum(_alloc)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _alignment_preserved_type;
  _alignment_preserved_type alignment_preserved;

   typedef uint8_t _switch_pending_type;
  _switch_pending_type switch_pending;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _active_map_type;
  _active_map_type active_map;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _active_map_uuid_type;
  _active_map_uuid_type active_map_uuid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pending_map_type;
  _pending_map_type pending_map;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pending_map_uuid_type;
  _pending_map_uuid_type pending_map_uuid;

   typedef uint32_t _map_schema_version_type;
  _map_schema_version_type map_schema_version;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _coordinate_frame_type;
  _coordinate_frame_type coordinate_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _origin_checksum_type;
  _origin_checksum_type origin_checksum;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;





  typedef boost::shared_ptr< ::util::ManageLocalizationMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::ManageLocalizationMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ManageLocalizationMapResponse_

typedef ::util::ManageLocalizationMapResponse_<std::allocator<void> > ManageLocalizationMapResponse;

typedef boost::shared_ptr< ::util::ManageLocalizationMapResponse > ManageLocalizationMapResponsePtr;
typedef boost::shared_ptr< ::util::ManageLocalizationMapResponse const> ManageLocalizationMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::ManageLocalizationMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::ManageLocalizationMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::ManageLocalizationMapResponse_<ContainerAllocator1> & lhs, const ::util::ManageLocalizationMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.alignment_preserved == rhs.alignment_preserved &&
    lhs.switch_pending == rhs.switch_pending &&
    lhs.active_map == rhs.active_map &&
    lhs.active_map_uuid == rhs.active_map_uuid &&
    lhs.pending_map == rhs.pending_map &&
    lhs.pending_map_uuid == rhs.pending_map_uuid &&
    lhs.map_schema_version == rhs.map_schema_version &&
    lhs.coordinate_frame == rhs.coordinate_frame &&
    lhs.origin_checksum == rhs.origin_checksum &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::ManageLocalizationMapResponse_<ContainerAllocator1> & lhs, const ::util::ManageLocalizationMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::ManageLocalizationMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::ManageLocalizationMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::ManageLocalizationMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::ManageLocalizationMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::ManageLocalizationMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::ManageLocalizationMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::ManageLocalizationMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "839a6a6f72eca859c62078e8cacaeaf4";
  }

  static const char* value(const ::util::ManageLocalizationMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x839a6a6f72eca859ULL;
  static const uint64_t static_value2 = 0xc62078e8cacaeaf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::ManageLocalizationMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/ManageLocalizationMapResponse";
  }

  static const char* value(const ::util::ManageLocalizationMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::ManageLocalizationMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"bool alignment_preserved\n"
"bool switch_pending\n"
"string active_map\n"
"string active_map_uuid\n"
"string pending_map\n"
"string pending_map_uuid\n"
"uint32 map_schema_version\n"
"string coordinate_frame\n"
"string origin_checksum\n"
"string reason\n"
"\n"
;
  }

  static const char* value(const ::util::ManageLocalizationMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::ManageLocalizationMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.alignment_preserved);
      stream.next(m.switch_pending);
      stream.next(m.active_map);
      stream.next(m.active_map_uuid);
      stream.next(m.pending_map);
      stream.next(m.pending_map_uuid);
      stream.next(m.map_schema_version);
      stream.next(m.coordinate_frame);
      stream.next(m.origin_checksum);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManageLocalizationMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::ManageLocalizationMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::ManageLocalizationMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "alignment_preserved: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alignment_preserved);
    s << indent << "switch_pending: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.switch_pending);
    s << indent << "active_map: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.active_map);
    s << indent << "active_map_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.active_map_uuid);
    s << indent << "pending_map: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pending_map);
    s << indent << "pending_map_uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pending_map_uuid);
    s << indent << "map_schema_version: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.map_schema_version);
    s << indent << "coordinate_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.coordinate_frame);
    s << indent << "origin_checksum: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.origin_checksum);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_MANAGELOCALIZATIONMAPRESPONSE_H
