// Generated by gencpp from file util/ManageLocalizationMap.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_MANAGELOCALIZATIONMAP_H
#define UTIL_MESSAGE_MANAGELOCALIZATIONMAP_H

#include <ros/service_traits.h>


#include <util/ManageLocalizationMapRequest.h>
#include <util/ManageLocalizationMapResponse.h>


namespace util
{

struct ManageLocalizationMap
{

typedef ManageLocalizationMapRequest Request;
typedef ManageLocalizationMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManageLocalizationMap
} // namespace util


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::util::ManageLocalizationMap > {
  static const char* value()
  {
    return "f6eb786c2817a22f906c5e66a8ae611a";
  }

  static const char* value(const ::util::ManageLocalizationMap&) { return value(); }
};

template<>
struct DataType< ::util::ManageLocalizationMap > {
  static const char* value()
  {
    return "util/ManageLocalizationMap";
  }

  static const char* value(const ::util::ManageLocalizationMap&) { return value(); }
};


// service_traits::MD5Sum< ::util::ManageLocalizationMapRequest> should match
// service_traits::MD5Sum< ::util::ManageLocalizationMap >
template<>
struct MD5Sum< ::util::ManageLocalizationMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::util::ManageLocalizationMap >::value();
  }
  static const char* value(const ::util::ManageLocalizationMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::util::ManageLocalizationMapRequest> should match
// service_traits::DataType< ::util::ManageLocalizationMap >
template<>
struct DataType< ::util::ManageLocalizationMapRequest>
{
  static const char* value()
  {
    return DataType< ::util::ManageLocalizationMap >::value();
  }
  static const char* value(const ::util::ManageLocalizationMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::util::ManageLocalizationMapResponse> should match
// service_traits::MD5Sum< ::util::ManageLocalizationMap >
template<>
struct MD5Sum< ::util::ManageLocalizationMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::util::ManageLocalizationMap >::value();
  }
  static const char* value(const ::util::ManageLocalizationMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::util::ManageLocalizationMapResponse> should match
// service_traits::DataType< ::util::ManageLocalizationMap >
template<>
struct DataType< ::util::ManageLocalizationMapResponse>
{
  static const char* value()
  {
    return DataType< ::util::ManageLocalizationMap >::value();
  }
  static const char* value(const ::util::ManageLocalizationMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTIL_MESSAGE_MANAGELOCALIZATIONMAP_H
