// Generated by gencpp from file util/ManageLocalizationMapRequest.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_MANAGELOCALIZATIONMAPREQUEST_H
#define UTIL_MESSAGE_MANAGELOCALIZATIONMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace util
{
template <class ContainerAllocator>
struct ManageLocalizationMapRequest_
{
  typedef ManageLocalizationMapRequest_<ContainerAllocator> Type;

  ManageLocalizationMapRequest_()
    : command(0)
    , map_name()
    , overwrite(false)  {
    }
  ManageLocalizationMapRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , map_name(_alloc)
    , overwrite(false)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_name_type;
  _map_name_type map_name;

   typedef uint8_t _overwrite_type;
  _overwrite_type overwrite;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SAVE_CURRENT_AND_ACTIVATE)
  #undef SAVE_CURRENT_AND_ACTIVATE
#endif
#if defined(_WIN32) && defined(ACTIVATE_EXISTING)
  #undef ACTIVATE_EXISTING
#endif

  enum {
    SAVE_CURRENT_AND_ACTIVATE = 1u,
    ACTIVATE_EXISTING = 2u,
  };


  typedef boost::shared_ptr< ::util::ManageLocalizationMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::ManageLocalizationMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ManageLocalizationMapRequest_

typedef ::util::ManageLocalizationMapRequest_<std::allocator<void> > ManageLocalizationMapRequest;

typedef boost::shared_ptr< ::util::ManageLocalizationMapRequest > ManageLocalizationMapRequestPtr;
typedef boost::shared_ptr< ::util::ManageLocalizationMapRequest const> ManageLocalizationMapRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::ManageLocalizationMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::ManageLocalizationMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::ManageLocalizationMapRequest_<ContainerAllocator1> & lhs, const ::util::ManageLocalizationMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.map_name == rhs.map_name &&
    lhs.overwrite == rhs.overwrite;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::ManageLocalizationMapRequest_<ContainerAllocator1> & lhs, const ::util::ManageLocalizationMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::ManageLocalizationMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::ManageLocalizationMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::ManageLocalizationMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::ManageLocalizationMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::ManageLocalizationMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::ManageLocalizationMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::ManageLocalizationMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97835c85afd8e1d5520dfc73f4fbb216";
  }

  static const char* value(const ::util::ManageLocalizationMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97835c85afd8e1d5ULL;
  static const uint64_t static_value2 = 0x520dfc73f4fbb216ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::ManageLocalizationMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/ManageLocalizationMapRequest";
  }

  static const char* value(const ::util::ManageLocalizationMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::ManageLocalizationMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Transactional map lifecycle API owned by fusion_4dof.\n"
"uint8 SAVE_CURRENT_AND_ACTIVATE=1\n"
"uint8 ACTIVATE_EXISTING=2\n"
"\n"
"uint8 command\n"
"string map_name\n"
"bool overwrite\n"
;
  }

  static const char* value(const ::util::ManageLocalizationMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::ManageLocalizationMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.map_name);
      stream.next(m.overwrite);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManageLocalizationMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::ManageLocalizationMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::ManageLocalizationMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "map_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_name);
    s << indent << "overwrite: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.overwrite);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_MANAGELOCALIZATIONMAPREQUEST_H
