// Generated by gencpp from file util/Position.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_POSITION_H
#define UTIL_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : header()
    , position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , position_state(0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , position_state(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _position_x_type;
  _position_x_type position_x;

   typedef double _position_y_type;
  _position_y_type position_y;

   typedef double _position_z_type;
  _position_z_type position_z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef uint32_t _position_state_type;
  _position_state_type position_state;





  typedef boost::shared_ptr< ::util::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::util::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::util::Position > PositionPtr;
typedef boost::shared_ptr< ::util::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::Position_<ContainerAllocator1> & lhs, const ::util::Position_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_z == rhs.position_z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.position_state == rhs.position_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::Position_<ContainerAllocator1> & lhs, const ::util::Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::Position_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::Position_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b162b5fae3a9f45d1742394d3c0bb3a6";
  }

  static const char* value(const ::util::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb162b5fae3a9f45dULL;
  static const uint64_t static_value2 = 0x1742394d3c0bb3a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/Position";
  }

  static const char* value(const ::util::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 通用定位输出。修改注释不会改变ROS消息MD5；字段、类型和顺序不得随意修改，\n"
"# 否则所有util/Position生产者、消费者必须同步重新编译和部署。\n"
"Header header\n"
"\n"
"# 位置单位：m；姿态单位：rad。\n"
"# 当前fusion_4dof在/Mower/position上发布的是“base_link在地图ENU中的位姿”：\n"
"# position_x=East，position_y=North，position_z=Up；roll/pitch/yaw遵循ROS\n"
"# base_link约定。为兼容既有下游，header.frame_id当前仍填\"base_link\"，因此不能\n"
"# 仅按frame_id把position_*误解为车体系坐标。\n"
"# 旧SE2生产者的地图坐标定义不同；两版并行对照时必须使用不同输出话题，且不能\n"
"# 不经坐标转换直接逐点相减。\n"
"float64 position_x\n"
"float64 position_y\n"
"float64 position_z\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"\n"
"# /Mower/position的position_state取值（调试话题可能复用该字段表达自身布尔状态，\n"
"# 不得把调试话题的0/1直接套用以下生产定位语义）：\n"
"#   0 = 无有效生产定位/保留值；不得驱动车辆作业\n"
"#   1 = GPS/RTK正常：x/y/yaw以GPS/组合导航为主；同步RTK短暂缺帧的配置宽限内，\n"
"#       使用“最后可信RTK锚点+LIO相对增量”短时延拓；z使用LIO相对高程+稳健tz\n"
"#   2 = 4DoF LIO回退，水平yaw已锁定（经过二维展布充分的鲁棒Umeyama拟合）\n"
"#   3 = 纯GPS调试模式（pub_fusion==2），不得等同于正常自动融合状态1\n"
"#   4 = 纯LIO调试模式（pub_fusion==3）；只有完整4DoF有效时才具有全局ENU语义\n"
"#   5 = 4DoF LIO回退，水平yaw仅播种未锁定（沿迹基线或RTK航向种子）；短时\n"
"#       可用，但长直线长时间丢RTK时误差风险高于状态2\n"
"#   6 = MID360 IMU受限积分里程计；仅用于制动期位姿连续，\n"
"#       不得自动作业，超过时间/距离/数据新鲜度门限立即失效\n"
"#   9 = 航向尚未初始化（heading_flag_为假时覆盖输出状态）；不得驱动车辆作业\n"
"# 当前生产控制中只有1/2/5属于“有效可用位置”；所有按状态判断定位有效性的\n"
"# 消费者都必须显式包含5，并可对状态5采用更保守的速度/作业策略。\n"
"uint32 position_state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.position_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::Position_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position_x: ";
    Printer<double>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<double>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_z: ";
    Printer<double>::stream(s, indent + "  ", v.position_z);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "position_state: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.position_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_POSITION_H
