(cl:defpackage util-msg
  (:use )
  (:export
   "<DIAGNOSTICRESULT>"
   "DIAGNOSTICRESULT"
   "<GPSPOSITION>"
   "GPSPOSITION"
   "<LOCALPATH>"
   "LOCALPATH"
   "<LOCALPOSE>"
   "LOCALPOSE"
   "<MAPPATH>"
   "MAPPATH"
   "<POLYGONWITHHOLES>"
   "POLYGONWITHHOLES"
   "<POLYGONWITHHOLESSTAMPED>"
   "POLYGONWITHHOLESSTAMPED"
   "<POSITION>"
   "POSITION"
  ))

