(cl:in-package util-msg)
(cl:export '(HEADER-VAL
          HEADER
          PLAT_ID-VAL
          PLAT_ID
          ERROR_CODE-VAL
          ERROR_CODE
          GPS_FLAG-VAL
          GPS_FLAG
          POSITIONSTATUS-VAL
          POSITIONSTATUS
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECOND-VAL
          GPS_MILLISECOND
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          HEIGHT-VAL
          HEIGHT
          GAUSSX-VAL
          GAUSSX
          GAUSSY-VAL
          GAUSSY
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          AZIMUTH-VAL
          AZIMUTH
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          ROT_X-VAL
          ROT_X
          ROT_Y-VAL
          ROT_Y
          ROT_Z-VAL
          ROT_Z
          NORTHVELOCITY-VAL
          NORTHVELOCITY
          EASTVELOCITY-VAL
          EASTVELOCITY
          UPVELOCITY-VAL
          UPVELOCITY
          GPS_CONFIDENCE-VAL
          GPS_CONFIDENCE
          INS_GPSFLAG_POS-VAL
          INS_GPSFLAG_POS
          INS_NUMSV-VAL
          INS_NUMSV
          INS_GPSFLAG_HEADING-VAL
          INS_GPSFLAG_HEADING
          INS_GPS_AGE-VAL
          INS_GPS_AGE
          INS_CAR_STATUS-VAL
          INS_CAR_STATUS
          INS_STATUS-VAL
          INS_STATUS
          INS_VEHICLEALIGN-VAL
          INS_VEHICLEALIGN
          INS_STD_LAT-VAL
          INS_STD_LAT
          INS_STD_LON-VAL
          INS_STD_LON
          INS_STD_LOCATHEIGHT-VAL
          INS_STD_LOCATHEIGHT
          INS_STD_HEADING-VAL
          INS_STD_HEADING
))