// Generated by gencpp from file util/DiagnosticResult.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_DIAGNOSTICRESULT_H
#define UTIL_MESSAGE_DIAGNOSTICRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct DiagnosticResult_
{
  typedef DiagnosticResult_<ContainerAllocator> Type;

  DiagnosticResult_()
    : header()
    , fault_code(0)  {
    }
  DiagnosticResult_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fault_code(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _fault_code_type;
  _fault_code_type fault_code;





  typedef boost::shared_ptr< ::util::DiagnosticResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::DiagnosticResult_<ContainerAllocator> const> ConstPtr;

}; // struct DiagnosticResult_

typedef ::util::DiagnosticResult_<std::allocator<void> > DiagnosticResult;

typedef boost::shared_ptr< ::util::DiagnosticResult > DiagnosticResultPtr;
typedef boost::shared_ptr< ::util::DiagnosticResult const> DiagnosticResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::DiagnosticResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::DiagnosticResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::DiagnosticResult_<ContainerAllocator1> & lhs, const ::util::DiagnosticResult_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fault_code == rhs.fault_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::DiagnosticResult_<ContainerAllocator1> & lhs, const ::util::DiagnosticResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::DiagnosticResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::DiagnosticResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::DiagnosticResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::DiagnosticResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::DiagnosticResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::DiagnosticResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::DiagnosticResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d380b94db25b373da53086abf486f7d3";
  }

  static const char* value(const ::util::DiagnosticResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd380b94db25b373dULL;
  static const uint64_t static_value2 = 0xa53086abf486f7d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::DiagnosticResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/DiagnosticResult";
  }

  static const char* value(const ::util::DiagnosticResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::DiagnosticResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Diagnostic status code\n"
"# 0: Normal operation\n"
"# 1: No position data (/Mower/position)\n"
"# 2: Stop car command received (/mower/stop_car=true)\n"
"# 3: Emergency stop for obstacle avoidance (/lawn_mower/avoid_state==3)\n"
"# 4: No global path (/lawn_mower/global_path)\n"
"# 5: PID controller node not running (pid_controller node)\n"
"# 6: CAN communication buffer full (fallback check when others are normal)\n"
"uint8 fault_code \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::DiagnosticResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::DiagnosticResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fault_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiagnosticResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::DiagnosticResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::DiagnosticResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fault_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fault_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_DIAGNOSTICRESULT_H
