// Generated by gencpp from file util/PolygonWithHoles.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_POLYGONWITHHOLES_H
#define UTIL_MESSAGE_POLYGONWITHHOLES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Polygon.h>
#include <geometry_msgs/Polygon.h>

namespace util
{
template <class ContainerAllocator>
struct PolygonWithHoles_
{
  typedef PolygonWithHoles_<ContainerAllocator> Type;

  PolygonWithHoles_()
    : hull()
    , holes()  {
    }
  PolygonWithHoles_(const ContainerAllocator& _alloc)
    : hull(_alloc)
    , holes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Polygon_<ContainerAllocator>  _hull_type;
  _hull_type hull;

   typedef std::vector< ::geometry_msgs::Polygon_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Polygon_<ContainerAllocator> >> _holes_type;
  _holes_type holes;





  typedef boost::shared_ptr< ::util::PolygonWithHoles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::PolygonWithHoles_<ContainerAllocator> const> ConstPtr;

}; // struct PolygonWithHoles_

typedef ::util::PolygonWithHoles_<std::allocator<void> > PolygonWithHoles;

typedef boost::shared_ptr< ::util::PolygonWithHoles > PolygonWithHolesPtr;
typedef boost::shared_ptr< ::util::PolygonWithHoles const> PolygonWithHolesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::PolygonWithHoles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::PolygonWithHoles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::PolygonWithHoles_<ContainerAllocator1> & lhs, const ::util::PolygonWithHoles_<ContainerAllocator2> & rhs)
{
  return lhs.hull == rhs.hull &&
    lhs.holes == rhs.holes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::PolygonWithHoles_<ContainerAllocator1> & lhs, const ::util::PolygonWithHoles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::PolygonWithHoles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::PolygonWithHoles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::PolygonWithHoles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::PolygonWithHoles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::PolygonWithHoles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::PolygonWithHoles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::PolygonWithHoles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "172a5c8423a33d0cd317c84e16aead83";
  }

  static const char* value(const ::util::PolygonWithHoles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x172a5c8423a33d0cULL;
  static const uint64_t static_value2 = 0xd317c84e16aead83ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::PolygonWithHoles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/PolygonWithHoles";
  }

  static const char* value(const ::util::PolygonWithHoles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::PolygonWithHoles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A message to define a polygon with holes.\n"
"geometry_msgs/Polygon hull\n"
"geometry_msgs/Polygon[] holes\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::util::PolygonWithHoles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::PolygonWithHoles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hull);
      stream.next(m.holes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolygonWithHoles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::PolygonWithHoles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::PolygonWithHoles_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "hull: ";
    Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.hull);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "holes: ";
    if (v.holes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.holes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.holes[i]);
    }
    if (v.holes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_POLYGONWITHHOLES_H
