// Generated by gencpp from file util/PolygonWithHolesStamped.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_POLYGONWITHHOLESSTAMPED_H
#define UTIL_MESSAGE_POLYGONWITHHOLESSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <util/PolygonWithHoles.h>

namespace util
{
template <class ContainerAllocator>
struct PolygonWithHolesStamped_
{
  typedef PolygonWithHolesStamped_<ContainerAllocator> Type;

  PolygonWithHolesStamped_()
    : header()
    , polygon()  {
    }
  PolygonWithHolesStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , polygon(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::util::PolygonWithHoles_<ContainerAllocator>  _polygon_type;
  _polygon_type polygon;





  typedef boost::shared_ptr< ::util::PolygonWithHolesStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::PolygonWithHolesStamped_<ContainerAllocator> const> ConstPtr;

}; // struct PolygonWithHolesStamped_

typedef ::util::PolygonWithHolesStamped_<std::allocator<void> > PolygonWithHolesStamped;

typedef boost::shared_ptr< ::util::PolygonWithHolesStamped > PolygonWithHolesStampedPtr;
typedef boost::shared_ptr< ::util::PolygonWithHolesStamped const> PolygonWithHolesStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::PolygonWithHolesStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::PolygonWithHolesStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::PolygonWithHolesStamped_<ContainerAllocator1> & lhs, const ::util::PolygonWithHolesStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.polygon == rhs.polygon;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::PolygonWithHolesStamped_<ContainerAllocator1> & lhs, const ::util::PolygonWithHolesStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::PolygonWithHolesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::PolygonWithHolesStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::PolygonWithHolesStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::PolygonWithHolesStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::PolygonWithHolesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::PolygonWithHolesStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::PolygonWithHolesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11ecbf0df20ddfcc1b6166cf645d78f1";
  }

  static const char* value(const ::util::PolygonWithHolesStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11ecbf0df20ddfccULL;
  static const uint64_t static_value2 = 0x1b6166cf645d78f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::PolygonWithHolesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/PolygonWithHolesStamped";
  }

  static const char* value(const ::util::PolygonWithHolesStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::PolygonWithHolesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A stamped polygon with holes.\n"
"std_msgs/Header header\n"
"util/PolygonWithHoles polygon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: util/PolygonWithHoles\n"
"# A message to define a polygon with holes.\n"
"geometry_msgs/Polygon hull\n"
"geometry_msgs/Polygon[] holes\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::util::PolygonWithHolesStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::PolygonWithHolesStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.polygon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolygonWithHolesStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::PolygonWithHolesStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::PolygonWithHolesStamped_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "polygon: ";
    Printer< ::util::PolygonWithHoles_<ContainerAllocator> >::stream(s, indent + "  ", v.polygon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_POLYGONWITHHOLESSTAMPED_H
