// Generated by gencpp from file util/PlanningMapPoint.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_PLANNINGMAPPOINT_H
#define UTIL_MESSAGE_PLANNINGMAPPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct PlanningMapPoint_
{
  typedef PlanningMapPoint_<ContainerAllocator> Type;

  PlanningMapPoint_()
    : header()
    , global_x(0.0)
    , global_y(0.0)
    , obstacle_status(false)
    , track_status(false)  {
    }
  PlanningMapPoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , global_x(0.0)
    , global_y(0.0)
    , obstacle_status(false)
    , track_status(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _global_x_type;
  _global_x_type global_x;

   typedef double _global_y_type;
  _global_y_type global_y;

   typedef uint8_t _obstacle_status_type;
  _obstacle_status_type obstacle_status;

   typedef uint8_t _track_status_type;
  _track_status_type track_status;





  typedef boost::shared_ptr< ::util::PlanningMapPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::PlanningMapPoint_<ContainerAllocator> const> ConstPtr;

}; // struct PlanningMapPoint_

typedef ::util::PlanningMapPoint_<std::allocator<void> > PlanningMapPoint;

typedef boost::shared_ptr< ::util::PlanningMapPoint > PlanningMapPointPtr;
typedef boost::shared_ptr< ::util::PlanningMapPoint const> PlanningMapPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::PlanningMapPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::PlanningMapPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::PlanningMapPoint_<ContainerAllocator1> & lhs, const ::util::PlanningMapPoint_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.global_x == rhs.global_x &&
    lhs.global_y == rhs.global_y &&
    lhs.obstacle_status == rhs.obstacle_status &&
    lhs.track_status == rhs.track_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::PlanningMapPoint_<ContainerAllocator1> & lhs, const ::util::PlanningMapPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::PlanningMapPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::PlanningMapPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::PlanningMapPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::PlanningMapPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::PlanningMapPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::PlanningMapPoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::PlanningMapPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba8804762a910657104542279037ab6a";
  }

  static const char* value(const ::util::PlanningMapPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba8804762a910657ULL;
  static const uint64_t static_value2 = 0x104542279037ab6aULL;
};

template<class ContainerAllocator>
struct DataType< ::util::PlanningMapPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/PlanningMapPoint";
  }

  static const char* value(const ::util::PlanningMapPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::PlanningMapPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Global_Map_Point\n"
"float64 global_x\n"
"float64 global_y\n"
"bool obstacle_status\n"
"bool track_status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::PlanningMapPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::PlanningMapPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.global_x);
      stream.next(m.global_y);
      stream.next(m.obstacle_status);
      stream.next(m.track_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanningMapPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::PlanningMapPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::PlanningMapPoint_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "global_x: ";
    Printer<double>::stream(s, indent + "  ", v.global_x);
    s << indent << "global_y: ";
    Printer<double>::stream(s, indent + "  ", v.global_y);
    s << indent << "obstacle_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstacle_status);
    s << indent << "track_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.track_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_PLANNINGMAPPOINT_H
