// Generated by gencpp from file util/PlanningMapPointList.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_PLANNINGMAPPOINTLIST_H
#define UTIL_MESSAGE_PLANNINGMAPPOINTLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <util/PlanningMapPoint.h>

namespace util
{
template <class ContainerAllocator>
struct PlanningMapPointList_
{
  typedef PlanningMapPointList_<ContainerAllocator> Type;

  PlanningMapPointList_()
    : header()
    , global_point_list()  {
    }
  PlanningMapPointList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , global_point_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::util::PlanningMapPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::util::PlanningMapPoint_<ContainerAllocator> >> _global_point_list_type;
  _global_point_list_type global_point_list;





  typedef boost::shared_ptr< ::util::PlanningMapPointList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::PlanningMapPointList_<ContainerAllocator> const> ConstPtr;

}; // struct PlanningMapPointList_

typedef ::util::PlanningMapPointList_<std::allocator<void> > PlanningMapPointList;

typedef boost::shared_ptr< ::util::PlanningMapPointList > PlanningMapPointListPtr;
typedef boost::shared_ptr< ::util::PlanningMapPointList const> PlanningMapPointListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::PlanningMapPointList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::PlanningMapPointList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::PlanningMapPointList_<ContainerAllocator1> & lhs, const ::util::PlanningMapPointList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.global_point_list == rhs.global_point_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::PlanningMapPointList_<ContainerAllocator1> & lhs, const ::util::PlanningMapPointList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::PlanningMapPointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::PlanningMapPointList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::PlanningMapPointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::PlanningMapPointList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::PlanningMapPointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::PlanningMapPointList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::PlanningMapPointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e74b8cb2e54b9905429e9e007420b366";
  }

  static const char* value(const ::util::PlanningMapPointList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe74b8cb2e54b9905ULL;
  static const uint64_t static_value2 = 0x429e9e007420b366ULL;
};

template<class ContainerAllocator>
struct DataType< ::util::PlanningMapPointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/PlanningMapPointList";
  }

  static const char* value(const ::util::PlanningMapPointList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::PlanningMapPointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"PlanningMapPoint[] global_point_list\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: util/PlanningMapPoint\n"
"Header header\n"
"\n"
"# Global_Map_Point\n"
"float64 global_x\n"
"float64 global_y\n"
"bool obstacle_status\n"
"bool track_status\n"
;
  }

  static const char* value(const ::util::PlanningMapPointList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::PlanningMapPointList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.global_point_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanningMapPointList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::PlanningMapPointList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::PlanningMapPointList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "global_point_list[]" << std::endl;
    for (size_t i = 0; i < v.global_point_list.size(); ++i)
    {
      s << indent << "  global_point_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::util::PlanningMapPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.global_point_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_PLANNINGMAPPOINTLIST_H
