// Generated by gencpp from file util/VehicleBrakeCmd.msg
// DO NOT EDIT!


#ifndef UTIL_MESSAGE_VEHICLEBRAKECMD_H
#define UTIL_MESSAGE_VEHICLEBRAKECMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace util
{
template <class ContainerAllocator>
struct VehicleBrakeCmd_
{
  typedef VehicleBrakeCmd_<ContainerAllocator> Type;

  VehicleBrakeCmd_()
    : header()
    , BrakeCmd(false)  {
    }
  VehicleBrakeCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , BrakeCmd(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _BrakeCmd_type;
  _BrakeCmd_type BrakeCmd;





  typedef boost::shared_ptr< ::util::VehicleBrakeCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::util::VehicleBrakeCmd_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleBrakeCmd_

typedef ::util::VehicleBrakeCmd_<std::allocator<void> > VehicleBrakeCmd;

typedef boost::shared_ptr< ::util::VehicleBrakeCmd > VehicleBrakeCmdPtr;
typedef boost::shared_ptr< ::util::VehicleBrakeCmd const> VehicleBrakeCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::util::VehicleBrakeCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::util::VehicleBrakeCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::util::VehicleBrakeCmd_<ContainerAllocator1> & lhs, const ::util::VehicleBrakeCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.BrakeCmd == rhs.BrakeCmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::util::VehicleBrakeCmd_<ContainerAllocator1> & lhs, const ::util::VehicleBrakeCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::util::VehicleBrakeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::util::VehicleBrakeCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::VehicleBrakeCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::util::VehicleBrakeCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::VehicleBrakeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::util::VehicleBrakeCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::util::VehicleBrakeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0effc161a91329ac582a70b1515cb00a";
  }

  static const char* value(const ::util::VehicleBrakeCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0effc161a91329acULL;
  static const uint64_t static_value2 = 0x582a70b1515cb00aULL;
};

template<class ContainerAllocator>
struct DataType< ::util::VehicleBrakeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "util/VehicleBrakeCmd";
  }

  static const char* value(const ::util::VehicleBrakeCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::util::VehicleBrakeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"bool BrakeCmd #刹车信号\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::util::VehicleBrakeCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::util::VehicleBrakeCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.BrakeCmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleBrakeCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::util::VehicleBrakeCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::util::VehicleBrakeCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "BrakeCmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BrakeCmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTIL_MESSAGE_VEHICLEBRAKECMD_H
