(cl:in-package util-srv)
(cl:export '(COMMAND-VAL
          COMMAND
          MAP_NAME-VAL
          MAP_NAME
          OVERWRITE-VAL
          OVERWRITE
          SUCCESS-VAL
          SUCCESS
          ALIGNMENT_PRESERVED-VAL
          ALIGNMENT_PRESERVED
          SWITCH_PENDING-VAL
          SWITCH_PENDING
          ACTIVE_MAP-VAL
          ACTIVE_MAP
          ACTIVE_MAP_UUID-VAL
          ACTIVE_MAP_UUID
          PENDING_MAP-VAL
          PENDING_MAP
          PENDING_MAP_UUID-VAL
          PENDING_MAP_UUID
          MAP_SCHEMA_VERSION-VAL
          MAP_SCHEMA_VERSION
          COORDINATE_FRAME-VAL
          COORDINATE_FRAME
          ORIGIN_CHECKSUM-VAL
          ORIGIN_CHECKSUM
          REASON-VAL
          REASON
))