# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from util/moving_object.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class moving_object(genpy.Message):
  _md5sum = "7cd6ca358df051582ae0af990bcae84b"
  _type = "util/moving_object"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#relative position, m
float32 x1 # x_min
float32 y1 # y_min
float32 x2 # x_min
float32 y2 # y_max
float32 x3 # x_max
float32 y3 # y_max
float32 x4 # x_max
float32 y4 # y_min

# height, cm
float32 zmin

float32 zmax

# absolute speed, m/s
float32 speed

# deg
float32 speed_direction

uint32 id
string label

# center point coordinate in localpose frame, m
float32 global_x
float32 global_y

float32 local_x
float32 local_y"""
  __slots__ = ['x1','y1','x2','y2','x3','y3','x4','y4','zmin','zmax','speed','speed_direction','id','label','global_x','global_y','local_x','local_y']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','uint32','string','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x1,y1,x2,y2,x3,y3,x4,y4,zmin,zmax,speed,speed_direction,id,label,global_x,global_y,local_x,local_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(moving_object, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x1 is None:
        self.x1 = 0.
      if self.y1 is None:
        self.y1 = 0.
      if self.x2 is None:
        self.x2 = 0.
      if self.y2 is None:
        self.y2 = 0.
      if self.x3 is None:
        self.x3 = 0.
      if self.y3 is None:
        self.y3 = 0.
      if self.x4 is None:
        self.x4 = 0.
      if self.y4 is None:
        self.y4 = 0.
      if self.zmin is None:
        self.zmin = 0.
      if self.zmax is None:
        self.zmax = 0.
      if self.speed is None:
        self.speed = 0.
      if self.speed_direction is None:
        self.speed_direction = 0.
      if self.id is None:
        self.id = 0
      if self.label is None:
        self.label = ''
      if self.global_x is None:
        self.global_x = 0.
      if self.global_y is None:
        self.global_y = 0.
      if self.local_x is None:
        self.local_x = 0.
      if self.local_y is None:
        self.local_y = 0.
    else:
      self.x1 = 0.
      self.y1 = 0.
      self.x2 = 0.
      self.y2 = 0.
      self.x3 = 0.
      self.y3 = 0.
      self.x4 = 0.
      self.y4 = 0.
      self.zmin = 0.
      self.zmax = 0.
      self.speed = 0.
      self.speed_direction = 0.
      self.id = 0
      self.label = ''
      self.global_x = 0.
      self.global_y = 0.
      self.local_x = 0.
      self.local_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12fI().pack(_x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4, _x.zmin, _x.zmax, _x.speed, _x.speed_direction, _x.id))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4f().pack(_x.global_x, _x.global_y, _x.local_x, _x.local_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4, _x.zmin, _x.zmax, _x.speed, _x.speed_direction, _x.id,) = _get_struct_12fI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.global_x, _x.global_y, _x.local_x, _x.local_y,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12fI().pack(_x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4, _x.zmin, _x.zmax, _x.speed, _x.speed_direction, _x.id))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4f().pack(_x.global_x, _x.global_y, _x.local_x, _x.local_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4, _x.zmin, _x.zmax, _x.speed, _x.speed_direction, _x.id,) = _get_struct_12fI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.global_x, _x.global_y, _x.local_x, _x.local_y,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12fI = None
def _get_struct_12fI():
    global _struct_12fI
    if _struct_12fI is None:
        _struct_12fI = struct.Struct("<12fI")
    return _struct_12fI
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
