
(cl:in-package :asdf)

(defsystem "mower_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :std_msgs-msg
)
  :components ((:file "_package")
    (:file "CameraState" :depends-on ("_package_CameraState"))
    (:file "_package_CameraState" :depends-on ("_package"))
    (:file "CamerargbState" :depends-on ("_package_CamerargbState"))
    (:file "_package_CamerargbState" :depends-on ("_package"))
    (:file "CheckResult" :depends-on ("_package_CheckResult"))
    (:file "_package_CheckResult" :depends-on ("_package"))
    (:file "ControlError" :depends-on ("_package_ControlError"))
    (:file "_package_ControlError" :depends-on ("_package"))
    (:file "ControlOk" :depends-on ("_package_ControlOk"))
    (:file "_package_ControlOk" :depends-on ("_package"))
    (:file "ControlState" :depends-on ("_package_ControlState"))
    (:file "_package_ControlState" :depends-on ("_package"))
    (:file "Direct_Control" :depends-on ("_package_Direct_Control"))
    (:file "_package_Direct_Control" :depends-on ("_package"))
    (:file "Fault_Code" :depends-on ("_package_Fault_Code"))
    (:file "_package_Fault_Code" :depends-on ("_package"))
    (:file "GnssOK" :depends-on ("_package_GnssOK"))
    (:file "_package_GnssOK" :depends-on ("_package"))
    (:file "LidarSelfDtect" :depends-on ("_package_LidarSelfDtect"))
    (:file "_package_LidarSelfDtect" :depends-on ("_package"))
    (:file "LocalPath" :depends-on ("_package_LocalPath"))
    (:file "_package_LocalPath" :depends-on ("_package"))
    (:file "Manual_Driving_Cmd" :depends-on ("_package_Manual_Driving_Cmd"))
    (:file "_package_Manual_Driving_Cmd" :depends-on ("_package"))
    (:file "Manual_Set" :depends-on ("_package_Manual_Set"))
    (:file "_package_Manual_Set" :depends-on ("_package"))
    (:file "Monitor" :depends-on ("_package_Monitor"))
    (:file "_package_Monitor" :depends-on ("_package"))
    (:file "MultiMapSelfDetect" :depends-on ("_package_MultiMapSelfDetect"))
    (:file "_package_MultiMapSelfDetect" :depends-on ("_package"))
    (:file "PerceptionSelfDetect" :depends-on ("_package_PerceptionSelfDetect"))
    (:file "_package_PerceptionSelfDetect" :depends-on ("_package"))
    (:file "PlanType" :depends-on ("_package_PlanType"))
    (:file "_package_PlanType" :depends-on ("_package"))
    (:file "PlaningOK" :depends-on ("_package_PlaningOK"))
    (:file "_package_PlaningOK" :depends-on ("_package"))
    (:file "Position" :depends-on ("_package_Position"))
    (:file "_package_Position" :depends-on ("_package"))
    (:file "SegState" :depends-on ("_package_SegState"))
    (:file "_package_SegState" :depends-on ("_package"))
    (:file "TaskStatus" :depends-on ("_package_TaskStatus"))
    (:file "_package_TaskStatus" :depends-on ("_package"))
    (:file "TimeAreaLeft" :depends-on ("_package_TimeAreaLeft"))
    (:file "_package_TimeAreaLeft" :depends-on ("_package"))
    (:file "VehicleCmd" :depends-on ("_package_VehicleCmd"))
    (:file "_package_VehicleCmd" :depends-on ("_package"))
    (:file "VehicleInfo" :depends-on ("_package_VehicleInfo"))
    (:file "_package_VehicleInfo" :depends-on ("_package"))
    (:file "VehicleStatus" :depends-on ("_package_VehicleStatus"))
    (:file "_package_VehicleStatus" :depends-on ("_package"))
    (:file "Vslam" :depends-on ("_package_Vslam"))
    (:file "_package_Vslam" :depends-on ("_package"))
    (:file "VslamState" :depends-on ("_package_VslamState"))
    (:file "_package_VslamState" :depends-on ("_package"))
  ))